export {
  initDatabase,
  isDatabaseReady,
  getDatabase,
  closeDatabase,
  backupDatabaseFile,
  novelOps,
  characterOps,
  outlineOps,
  outlineVersionOps,
  storyIdeaOps,
  worldSettingOps,
  statsOps,
  settingsOps,
  aiCacheOps,
  videoTaskOps,
  exportAllData,
  importData,
  PROJECT_SEED_FILE,
  seedProjectData,
  validateProjectSeed,
  NOVEL_CONTENT_TABLES,
  countNovelContent,
  ensureNovelByFolder,
  hasNovelContentByFolder,
  migrateProjectContentToWork,
} from './database';
export { versionOps } from './versioning';

export type {
  ExportData,
  VideoTaskRecordLike,
  NovelContentCounts,
  ProjectSeedData,
  SeedCounts,
  SeedProjectResult,
  WorkContentMigration,
} from './database';
export type {
  OutlineScope,
  OutlineScopeKind,
  OutlineVersionRow,
  OutlineVersionSource,
  StoryIdeaCardRow,
  StoryIdeaCardSource,
  StoryIdeaCardStatus,
  StoryIdeaOutputRow,
  StoryIdeaOutputType,
} from './database';
export type { VersionSnapshotInfo, SnapshotFileContent, SnapshotProgress } from './versioning';
