import type { PersistedOutlineScopeInput } from '../../types/electron-api';

export type TabType = 'storyline' | 'characters' | 'lore';

export type StorylineViewMode = 'catalog' | 'outline' | 'acts';

export type LoreCategory = 'world' | 'faction' | 'system' | 'term';

export interface LoreEntry {
  id: number;
  title: string;
  summary: string;
  category: LoreCategory;
  tags: string[];
  createdAt: string;
  updatedAt: string;
}

export type RelationTone = 'ally' | 'rival' | 'family' | 'mentor' | 'other';

export interface CharacterRelation {
  id: string;
  sourceId: number;
  targetId: number;
  label: string;
  tone: RelationTone;
  note: string;
}

export interface PersistedAISettings {
  enabled?: boolean;
  contextTokens?: number;
  maxTokens?: number;
  temperature?: number;
}

export interface CharacterGraphAICharacter {
  name: string;
  role?: string;
  description?: string;
  aliases?: string[];
  highlight?: string;
}

export interface CharacterGraphAIRelation {
  source: string;
  target: string;
  label?: string;
  tone?: string;
  note?: string;
}

export interface CharacterGraphAIResult {
  characters: CharacterGraphAICharacter[];
  relations: CharacterGraphAIRelation[];
  summary: string;
}

export interface OutlineEntry {
  id?: number;
  parentId?: number | null;
  cacheKey: string;
  line: number;
  lineHint?: number | null;
  level: number;
  text: string;
  summary: string;
  autoGenerated: boolean;
  source?: 'document' | 'database';
  anchorText?: string;
  originalText?: string;
  needsAiTitle?: boolean;
  wordCount: number;
}

export type OutlineTitleDisplayMode = 'replace' | 'append';
export type OutlineAiState = 'idle' | 'loading' | 'success' | 'error';
export type OutlineSummaryAiState = 'idle' | 'loading' | 'success' | 'error';

export interface OutlinePopoverAnchor {
  line: number;
  rect: DOMRect;
}

export interface RightPanelProps {
  content: string;
  collapsed: boolean;
  enabled?: boolean;
  scopeKind?: 'project' | 'volume' | 'chapter';
  scopeLabel?: string;
  outlineScope?: PersistedOutlineScopeInput | null;
  onToggle: () => void;
  onPopOut?: () => void;
  onScrollToLine?: (line: number, contentKey?: string) => void;
  onReplaceLineText?: (line: number, text: string) => void;
  /** 打开某章并定位到行（卷纲点击其他章节时使用） */
  onOpenSourceLocation?: (filePath: string, line: number, contentKey?: string) => void;
  folderPath: string | null;
  dbReady: boolean;
}

export interface CharacterCurrentStateItem {
  id: string;
  label: string;
  value: string;
}

export interface Character {
  id: number;
  name: string;
  role: string;
  category: CharacterCategory;
  description: string;
  currentState: CharacterCurrentStateItem[];
  avatar?: string;
  aliases?: string[];
  highlightColor?: string;
  highlightFirstMentionOnly?: boolean;
}

export interface CharacterTimelineItem {
  id: string;
  title: string;
  summary: string;
  source: 'auto' | 'manual';
  autoKey?: string;
  mentionCount?: number;
  sourceLabel?: string;
  chapterLabel?: string;
  chapterNumber?: number;
  sourcePath?: string;
  startLine?: number;
  endLine?: number;
}

export interface CharacterLink {
  sourceId: number;
  targetId: number;
  label: string;
}

export type CharacterCategory = 'major' | 'secondary';
export type CharacterCamp = 'protagonist' | 'antagonist' | 'support';
