export type TabType = 'storyline' | 'characters' | 'lore';

export type StorylineViewMode = 'catalog' | 'outline' | 'acts' | 'ideas';

export type LoreCategory = 'world' | 'faction' | 'system' | 'term';

export interface LoreEntry {
  id: number;
  title: string;
  summary: string;
  category: LoreCategory;
  tags: string[];
  createdAt: string;
  updatedAt: string;
}

export type RelationTone = 'ally' | 'rival' | 'family' | 'mentor' | 'other';

export interface CharacterRelation {
  id: string;
  sourceId: number;
  targetId: number;
  label: string;
  tone: RelationTone;
  note: string;
}

export interface PlotSceneBoard {
  sceneKey: string;
  title: string;
  objective: string;
  tension: string;
  outcome: string;
  status: 'draft' | 'ready' | 'done';
  /** Characters involved in this scene */
  characters: string[];
  /** Beat notes within the scene */
  beats: string[];
  /** Causal link: key of the scene this scene causes/leads to */
  causesScene: string | null;
  /** POV character for swimlane placement */
  pov: string;
  /** Emotional intensity 1-5 for visual heat mapping */
  intensity: number;
}

export interface PlotActBoard {
  premise: string;
  goal: string;
  conflict: string;
  twist: string;
  payoff: string;
  structureNodes: string[];
  aiSuggestion: string;
  sceneBoards: PlotSceneBoard[];
}

export type StorylineLayoutMode = 'board' | 'timeline' | 'causal';

export interface PersistedAISettings {
  enabled?: boolean;
  contextTokens?: number;
  maxTokens?: number;
  temperature?: number;
}

export interface CharacterGraphAICharacter {
  name: string;
  role?: string;
  description?: string;
  aliases?: string[];
  highlight?: string;
}

export interface CharacterGraphAIRelation {
  source: string;
  target: string;
  label?: string;
  tone?: string;
  note?: string;
}

export interface CharacterGraphAIResult {
  characters: CharacterGraphAICharacter[];
  relations: CharacterGraphAIRelation[];
  summary: string;
}

export interface OutlineEntry {
  id?: number;
  parentId?: number | null;
  cacheKey: string;
  line: number;
  lineHint?: number | null;
  level: number;
  text: string;
  summary: string;
  autoGenerated: boolean;
  source?: 'document' | 'database';
  anchorText?: string;
  originalText?: string;
  needsAiTitle?: boolean;
  wordCount: number;
}

export type OutlineTitleDisplayMode = 'replace' | 'append';
export type OutlineAiState = 'idle' | 'loading' | 'success' | 'error';
export type OutlineSummaryAiState = 'idle' | 'loading' | 'success' | 'error';

export interface OutlinePopoverAnchor {
  line: number;
  rect: DOMRect;
}

export interface RightPanelProps {
  content: string;
  collapsed: boolean;
  onToggle: () => void;
  onPopOut?: () => void;
  onScrollToLine?: (line: number, contentKey?: string) => void;
  onReplaceLineText?: (line: number, text: string) => void;
  folderPath: string | null;
  dbReady: boolean;
  currentLine?: number;
}

export interface Character {
  id: number;
  name: string;
  role: string;
  description: string;
  avatar?: string;
}

export interface CharacterLink {
  sourceId: number;
  targetId: number;
  label: string;
}

export type CharacterCamp = 'protagonist' | 'antagonist' | 'support';
