import { useCallback, useEffect, useMemo, useRef, useState } from 'react';
import type { PersistedOutlineNodeInput, PersistedOutlineRow } from '@/render/types/electron-api';
import type { OutlineEntry } from './types';
import { buildOutlineTreeFromContent, buildOutlineTreeFromImports } from './outline-import';
import { buildOutlineEntries, fnv1a32 } from './utils';
import { extractOutline } from '@novel-editor/basic-algorithm';

function normalizeAnchorText(value: string): string {
  return value
    .replace(/^#+\s*/, '')
    .replace(/[：:]+$/, '')
    .replace(/\s+/g, '')
    .trim()
    .toLowerCase();
}

function buildAnchorIndex(lines: string[]): Map<string, number> {
  const index = new Map<string, number>();
  for (let i = 0; i < lines.length; i++) {
    const norm = normalizeAnchorText(lines[i]);
    if (norm && !index.has(norm)) {
      index.set(norm, i + 1);
    }
  }
  return index;
}

function resolveAnchorLineIndexed(
  anchorIndex: Map<string, number>,
  lines: string[],
  title: string,
  anchorText: string,
  lineHint: number | null
): number | null {
  const candidates = [anchorText, title].map((item) => normalizeAnchorText(item)).filter(Boolean);
  if (candidates.length === 0) {
    return typeof lineHint === 'number' && lineHint > 0 ? lineHint : null;
  }

  // Fast path: exact match in index
  for (const candidate of candidates) {
    const exact = anchorIndex.get(candidate);
    if (exact !== undefined) return exact;
  }

  // Fallback: substring match near lineHint
  const isMatch = (rawLine: string) => {
    const normalizedLine = normalizeAnchorText(rawLine);
    return candidates.some(
      (candidate) => normalizedLine === candidate || normalizedLine.includes(candidate)
    );
  };

  if (typeof lineHint === 'number' && lineHint > 0 && lineHint <= lines.length) {
    const windowStart = Math.max(0, lineHint - 4);
    const windowEnd = Math.min(lines.length, lineHint + 3);
    for (let index = windowStart; index < windowEnd; index += 1) {
      if (isMatch(lines[index])) return index + 1;
    }
  }

  return typeof lineHint === 'number' && lineHint > 0 ? lineHint : null;
}

function summarizeContent(value: string): string {
  const compact = value.replace(/\s+/g, ' ').trim();
  if (!compact) return '';
  return compact.length <= 180 ? compact : `${compact.slice(0, 180)}...`;
}

function buildEntriesFromRows(rows: PersistedOutlineRow[], content: string): OutlineEntry[] {
  if (rows.length === 0) return [];
  const lines = content.split(/\r?\n/);
  const anchorIndex = buildAnchorIndex(lines);

  const childrenMap = new Map<number | null, PersistedOutlineRow[]>();
  rows.forEach((row) => {
    const key = row.parent_id ?? null;
    const bucket = childrenMap.get(key);
    if (bucket) {
      bucket.push(row);
    } else {
      childrenMap.set(key, [row]);
    }
  });

  for (const bucket of childrenMap.values()) {
    bucket.sort((left, right) => left.sort_order - right.sort_order || left.id - right.id);
  }

  const flattened: OutlineEntry[] = [];
  let sequence = 1;

  const visit = (parentId: number | null, level: number) => {
    const nodes = childrenMap.get(parentId) || [];
    nodes.forEach((row) => {
      const summary = summarizeContent(row.content);
      const resolvedLine = resolveAnchorLineIndexed(
        anchorIndex,
        lines,
        row.title,
        row.anchor_text || row.title,
        row.line_hint
      );
      flattened.push({
        id: row.id,
        parentId: row.parent_id,
        cacheKey: fnv1a32(`${row.id}:${row.title}:${row.updated_at}`),
        line: sequence++,
        lineHint: resolvedLine,
        level,
        text: row.title,
        summary,
        autoGenerated: false,
        source: 'database',
        anchorText: row.anchor_text || row.title,
        originalText: row.title,
        needsAiTitle: false,
        wordCount: row.content.replace(/\s+/g, '').length,
      });
      visit(row.id, level + 1);
    });
  };

  visit(null, 1);
  return flattened;
}

async function writeOutlineTree(folderPath: string, entries: PersistedOutlineNodeInput[]) {
  return window.electron.ipcRenderer.invoke('db-outline-replace-by-folder', folderPath, entries);
}

export function useOutlineEntries(
  folderPath: string | null,
  content: string,
  dbReady: boolean,
  aiReady: boolean
) {
  // Debounce content changes for liveEntries (300ms) to avoid re-parsing on every keystroke
  const [debouncedContent, setDebouncedContent] = useState(content);
  const debounceRef = useRef<ReturnType<typeof setTimeout> | null>(null);
  useEffect(() => {
    debounceRef.current = setTimeout(() => setDebouncedContent(content), 300);
    return () => {
      if (debounceRef.current) clearTimeout(debounceRef.current);
    };
  }, [content]);

  const liveEntries = useMemo(() => {
    const headings = extractOutline(debouncedContent, { enableHeuristic: false });
    return buildOutlineEntries(debouncedContent, headings).map((entry) => ({
      ...entry,
      source: 'document' as const,
    }));
  }, [debouncedContent]);

  const [persistedRows, setPersistedRows] = useState<PersistedOutlineRow[]>([]);
  const [loading, setLoading] = useState(false);
  const [importing, setImporting] = useState(false);
  const [statusMessage, setStatusMessage] = useState('');

  const persistedEntries = useMemo(
    () => buildEntriesFromRows(persistedRows, content),
    [content, persistedRows]
  );

  const hasPersistedOutline = persistedEntries.length > 0;

  const loadPersisted = useCallback(async () => {
    if (!folderPath || !dbReady) {
      setPersistedRows([]);
      return;
    }
    setLoading(true);
    try {
      const rows = await window.electron.ipcRenderer.invoke(
        'db-outline-list-by-folder',
        folderPath
      );
      setPersistedRows(rows);
      setStatusMessage('');
    } catch (error) {
      setPersistedRows([]);
      setStatusMessage(error instanceof Error ? error.message : '加载大纲失败');
    } finally {
      setLoading(false);
    }
  }, [dbReady, folderPath]);

  useEffect(() => {
    void loadPersisted();
  }, [loadPersisted]);

  const importOutline = useCallback(async () => {
    if (!folderPath || !dbReady) {
      setStatusMessage('项目数据库尚未就绪，无法导入大纲');
      return;
    }

    setImporting(true);
    try {
      const result = await window.electron.ipcRenderer.invoke('import-structured-file');
      if (!result || result.previews.length === 0) {
        setStatusMessage('未选择可导入的大纲文件');
        return;
      }

      const tree = await buildOutlineTreeFromImports(result.previews, aiReady);
      if (tree.length === 0) {
        setStatusMessage('没有解析出可导入的大纲结构');
        return;
      }

      await writeOutlineTree(folderPath, tree);
      await loadPersisted();
      const importedCount = tree.length;
      const suffix = result.errors.length > 0 ? `，${result.errors.length} 个文件失败` : '';
      setStatusMessage(`已导入 ${importedCount} 个顶层节点${suffix}`);
    } catch (error) {
      setStatusMessage(error instanceof Error ? error.message : '导入大纲失败');
    } finally {
      setImporting(false);
    }
  }, [aiReady, dbReady, folderPath, loadPersisted]);

  const rebuildFromContent = useCallback(async () => {
    if (!folderPath || !dbReady) {
      setStatusMessage('项目数据库尚未就绪，无法同步正文目录');
      return;
    }

    const tree = buildOutlineTreeFromContent(content);
    if (tree.length === 0) {
      setStatusMessage('当前正文没有可同步的目录结构');
      return;
    }

    setImporting(true);
    try {
      await writeOutlineTree(folderPath, tree);
      await loadPersisted();
      setStatusMessage(`已从正文重建 ${tree.length} 个目录节点`);
    } catch (error) {
      setStatusMessage(error instanceof Error ? error.message : '重建目录失败');
    } finally {
      setImporting(false);
    }
  }, [content, dbReady, folderPath, loadPersisted]);

  const clearPersisted = useCallback(async () => {
    if (!folderPath || !dbReady) {
      setStatusMessage('项目数据库尚未就绪，无法清空大纲');
      return;
    }

    setImporting(true);
    try {
      await window.electron.ipcRenderer.invoke('db-outline-clear-by-folder', folderPath);
      setPersistedRows([]);
      setStatusMessage('已清空已入库大纲，目录将回退为正文实时解析');
    } catch (error) {
      setStatusMessage(error instanceof Error ? error.message : '清空大纲失败');
    } finally {
      setImporting(false);
    }
  }, [dbReady, folderPath]);

  const reorderEntries = useCallback(
    async (fromIndex: number, toIndex: number) => {
      if (!folderPath || !dbReady || !hasPersistedOutline) return;
      if (fromIndex === toIndex) return;

      // Only reorder top-level (parentId === null) entries for simplicity.
      // Build the ordered list of top-level IDs from persistedRows.
      const topLevelRows = persistedRows
        .filter((r) => r.parent_id === null)
        .sort((a, b) => a.sort_order - b.sort_order || a.id - b.id);

      if (fromIndex < 0 || fromIndex >= topLevelRows.length) return;
      if (toIndex < 0 || toIndex >= topLevelRows.length) return;

      const reordered = [...topLevelRows];
      const [moved] = reordered.splice(fromIndex, 1);
      reordered.splice(toIndex, 0, moved);

      const ids = reordered.map((r) => r.id);

      // Optimistic UI update
      const newRows = persistedRows.map((row) => {
        if (row.parent_id !== null) return row;
        const newOrder = ids.indexOf(row.id);
        return newOrder >= 0 ? { ...row, sort_order: newOrder } : row;
      });
      setPersistedRows(newRows);

      try {
        await window.electron.ipcRenderer.invoke('db-outline-reorder-by-folder', folderPath, ids);
      } catch {
        // Revert on failure
        await loadPersisted();
      }
    },
    [dbReady, folderPath, hasPersistedOutline, persistedRows, loadPersisted]
  );

  return {
    outlineEntries: hasPersistedOutline ? persistedEntries : liveEntries,
    hasPersistedOutline,
    loading,
    importing,
    statusMessage,
    importOutline,
    rebuildFromContent,
    clearPersisted,
    reorderEntries,
  };
}
