// @vitest-environment happy-dom
import { afterEach, beforeEach, describe, expect, it, vi } from 'vitest';
import { act, renderHook } from '@testing-library/react';
import type { OutlineEntry } from '@/render/components/RightPanel/types';
import { installElectronMock, uninstallElectronMock } from '../../hooks/electronMock';

// ─── 可控的 AI 配置 / 缓存上下文 ────────────────────────────────────────────
const ctx = vi.hoisted(() => ({
  aiReady: true,
  cache: {
    titleCache: new Map<string, string>(),
    summaryCache: new Map<string, string>(),
    cacheReady: true,
  },
}));

vi.mock('@/render/components/RightPanel/useAiConfig', () => ({
  useAiConfig: () => ({ ready: ctx.aiReady }),
}));
vi.mock('@/render/components/RightPanel/AiCacheContext', () => ({
  useAiCache: () => ctx.cache,
}));

import { useAiTitles } from '@/render/components/RightPanel/useAiTitles';
import { useAiSummaries } from '@/render/components/RightPanel/useAiSummaries';
import {
  getHistorySummary,
  getSeverityCounts,
  resultToMarkdown,
  tryParseJSON,
  useAiWorkflow,
  type AIResultItem,
} from '@/render/components/RightPanel/useAiWorkflow';

function entry(line: number, overrides: Partial<OutlineEntry> = {}): OutlineEntry {
  return {
    cacheKey: `k${line}`,
    line,
    level: 1,
    text: `第${line}章`,
    summary: `第${line}章摘要`,
    autoGenerated: false,
    needsAiTitle: true,
    originalText: `第${line}章`,
    wordCount: 10,
    ...overrides,
  };
}

interface Deferred<T> {
  promise: Promise<T>;
  resolve: (value: T) => void;
  reject: (error: unknown) => void;
}
function deferred<T>(): Deferred<T> {
  let resolve!: (value: T) => void;
  let reject!: (error: unknown) => void;
  const promise = new Promise<T>((res, rej) => {
    resolve = res;
    reject = rej;
  });
  return { promise, resolve, reject };
}

type Handler = (...args: unknown[]) => unknown;
function setup(routes: Record<string, Handler> = {}) {
  const mock = installElectronMock((channel, ...args) => routes[channel]?.(...args));
  const calls = (channel: string) =>
    mock.invoke.mock.calls.filter((call) => call[0] === channel).map((call) => call.slice(1));
  return { mock, calls };
}

const flush = async () => {
  await act(async () => {
    await Promise.resolve();
    await Promise.resolve();
    await Promise.resolve();
  });
};

beforeEach(() => {
  ctx.aiReady = true;
  ctx.cache.titleCache = new Map();
  ctx.cache.summaryCache = new Map();
  ctx.cache.cacheReady = true;
});

afterEach(() => {
  uninstallElectronMock();
  vi.useRealTimers();
  vi.restoreAllMocks();
});

// ═══════════════════════════════════════════════════════════════════════════
// useAiTitles
// ═══════════════════════════════════════════════════════════════════════════
describe('useAiTitles', () => {
  const CONTENT = '第1章\n正文\n第2章\n正文';
  const NO_VISIBLE = new Set<number>();

  it('缓存未就绪时不做任何解析', () => {
    ctx.cache.cacheReady = false;
    setup();
    const { result } = renderHook(() => useAiTitles(CONTENT, [entry(1)], null, NO_VISIBLE));
    expect(result.current.aiTitles).toEqual({});
    expect(result.current.aiStates).toEqual({});
  });

  it('持久缓存命中时直接返回标题，不发起请求', async () => {
    ctx.cache.titleCache.set('k1', '缓存标题');
    const { calls } = setup();
    const { result } = renderHook(() =>
      useAiTitles(CONTENT, [entry(1), entry(2, { needsAiTitle: false })], null, new Set([1]))
    );
    await flush();
    expect(result.current.aiTitles).toEqual({ 1: '缓存标题' });
    expect(result.current.aiStates).toEqual({ 1: 'success' });
    expect(calls('ai-request')).toHaveLength(0);
  });

  it('可见待补全条目在防抖后自动请求，并写入缓存与持久化', async () => {
    vi.useFakeTimers();
    const { calls } = setup({
      'ai-request': () => ({
        ok: true,
        text: '```json\n[{"line":1,"title":"雪夜"},{"line":2,"title":"追杀"}]\n```',
      }),
    });
    const entries = [entry(1), entry(2), entry(3)];
    const visible = new Set([1, 2]);
    const { result } = renderHook(() => useAiTitles(CONTENT, entries, 2, visible));
    expect(calls('ai-request')).toHaveLength(0);
    await act(async () => {
      await vi.advanceTimersByTimeAsync(320);
    });
    expect(calls('ai-request')).toHaveLength(1);
    const [payload] = calls('ai-request')[0] as [{ context: string }];
    // 当前行优先排序
    expect(payload.context.indexOf('line=2')).toBeLessThan(payload.context.indexOf('line=1'));
    expect(payload.context).not.toContain('line=3');
    expect(result.current.aiTitles).toEqual({ 1: '雪夜', 2: '追杀' });
    expect(result.current.aiStates).toMatchObject({ 1: 'success', 2: 'success' });
    expect(ctx.cache.titleCache.get('k1')).toBe('雪夜');
    expect(calls('ai-cache-set')).toEqual(
      expect.arrayContaining([
        ['k1', 'title', '雪夜'],
        ['k2', 'title', '追杀'],
      ])
    );
  });

  it('AI 未开启或正文为空时不请求', async () => {
    ctx.aiReady = false;
    const { calls } = setup();
    const { result } = renderHook(() => useAiTitles(CONTENT, [entry(1)], null, NO_VISIBLE));
    act(() => result.current.requestAiTitles([entry(1)]));
    ctx.aiReady = true;
    const empty = renderHook(() => useAiTitles('  ', [entry(1)], null, NO_VISIBLE));
    act(() => empty.result.current.requestAiTitles([entry(1)]));
    await flush();
    expect(calls('ai-request')).toHaveLength(0);
  });

  it('部分条目未返回标题时标记为错误，并可通过 retryFailedEntries 重试', async () => {
    let text = '[{"line":1,"title":"雪夜"}]';
    const { calls } = setup({ 'ai-request': () => ({ ok: true, text }) });
    const entries = [entry(1), entry(2)];
    const { result } = renderHook(() => useAiTitles(CONTENT, entries, null, NO_VISIBLE));
    act(() => result.current.requestAiTitles(entries));
    await flush();
    expect(result.current.aiStates).toEqual({ 1: 'success', 2: 'error' });
    expect(result.current.aiErrors).toEqual({ 2: '该章节未返回可用标题' });
    expect(result.current.failedAiEntries.map((e) => e.line)).toEqual([2]);

    text = '[{"line":2,"title":"追杀"}]';
    act(() => result.current.retryFailedEntries());
    await flush();
    expect(result.current.aiTitles).toEqual({ 1: '雪夜', 2: '追杀' });
    expect(result.current.aiErrors).toEqual({});
    // 第二次请求只包含失败的条目
    const [second] = calls('ai-request')[1] as [{ context: string }];
    expect(second.context).toContain('line=2');
    expect(second.context).not.toContain('line=1');
  });

  it('AI 返回 ok:false 或 IPC 抛错时记录错误信息', async () => {
    let mode: 'fail' | 'throw' | 'throwRaw' = 'fail';
    setup({
      'ai-request': () => {
        if (mode === 'throw') throw new Error('网络错误');
        if (mode === 'throwRaw') throw 'raw';
        return { ok: false, error: '额度不足' };
      },
    });
    const { result } = renderHook(() => useAiTitles(CONTENT, [entry(1)], null, NO_VISIBLE));
    act(() => result.current.requestAiTitles([entry(1)]));
    await flush();
    expect(result.current.aiStates).toEqual({ 1: 'error' });
    expect(result.current.aiErrors).toEqual({ 1: '额度不足' });

    mode = 'throw';
    act(() => result.current.retryAiEntry(entry(1)));
    await flush();
    expect(result.current.aiErrors).toEqual({ 1: '网络错误' });

    mode = 'throwRaw';
    act(() => result.current.retryAiEntry(entry(1)));
    await flush();
    expect(result.current.aiErrors).toEqual({ 1: 'AI 标题补全失败' });
  });

  it('ok:false 且无 error 时使用默认文案；空数组请求被忽略', async () => {
    const { calls } = setup({ 'ai-request': () => ({ ok: false }) });
    const { result } = renderHook(() => useAiTitles(CONTENT, [entry(1)], null, NO_VISIBLE));
    act(() => result.current.requestAiTitles([]));
    act(() => result.current.retryFailedEntries());
    expect(calls('ai-request')).toHaveLength(0);
    act(() => result.current.requestAiTitles([entry(1)]));
    await flush();
    expect(result.current.aiErrors).toEqual({ 1: 'AI 标题补全失败' });
  });

  it('按批次（5 条）与并发上限（3）排队请求，同一行去重', async () => {
    const pending: Array<Deferred<{ ok: boolean; text: string }>> = [];
    const { calls } = setup({
      'ai-request': () => {
        const d = deferred<{ ok: boolean; text: string }>();
        pending.push(d);
        return d.promise;
      },
    });
    const entries = Array.from({ length: 20 }, (_, i) => entry(i + 1));
    const { result } = renderHook(() => useAiTitles(CONTENT, entries, null, NO_VISIBLE));
    act(() => result.current.requestAiTitles([...entries, entry(1)]));
    await flush();
    expect(calls('ai-request')).toHaveLength(3);
    expect(Object.values(result.current.aiStates).filter((s) => s === 'loading')).toHaveLength(15);
    await act(async () => {
      pending[0].resolve({ ok: true, text: '[]' });
      await Promise.resolve();
    });
    await flush();
    expect(calls('ai-request')).toHaveLength(4);
  });

  it('发起前缓存已被填充的条目不会重复请求', async () => {
    const { calls } = setup({ 'ai-request': () => ({ ok: true, text: '[]' }) });
    const { result } = renderHook(() => useAiTitles(CONTENT, [entry(1)], null, NO_VISIBLE));
    ctx.cache.titleCache.set('k1', '已有');
    act(() => result.current.requestAiTitles([entry(1)]));
    await flush();
    expect(calls('ai-request')).toHaveLength(0);
  });

  it('正文变化后，过期的响应被丢弃', async () => {
    vi.useFakeTimers();
    const d = deferred<{ ok: boolean; text: string }>();
    setup({ 'ai-request': () => d.promise });
    const entries = [entry(1)];
    const { result, rerender } = renderHook(
      ({ content }) => useAiTitles(content, entries, null, NO_VISIBLE),
      { initialProps: { content: CONTENT } }
    );
    act(() => result.current.requestAiTitles(entries));
    rerender({ content: CONTENT + '\n新增' });
    await act(async () => {
      await vi.advanceTimersByTimeAsync(300);
    });
    await act(async () => {
      d.resolve({ ok: true, text: '[{"line":1,"title":"过期"}]' });
      await vi.advanceTimersByTimeAsync(0);
    });
    expect(result.current.aiTitles).toEqual({});
    expect(ctx.cache.titleCache.has('k1')).toBe(false);
  });

  // BUG: useAiTitles.ts runBatch 在 `generation !== requestGenerationRef.current` 时直接 return，
  // 但请求前已把该条目置为 'loading'，过期分支从不复位。正文变化（例如编辑其他章节，cacheKey 不变）
  // 后，该条目永久停在 'loading'：Resolution 阶段把它计入 loadingCount 而不是 pending，
  // 自动预取再也不会重新请求它，界面上一直转圈。
  it('BUG: 过期响应被丢弃后条目不应永久停留在 loading', async () => {
    vi.useFakeTimers();
    const d = deferred<{ ok: boolean; text: string }>();
    setup({ 'ai-request': () => d.promise });
    const entries = [entry(1)];
    const { result, rerender } = renderHook(
      ({ content }) => useAiTitles(content, entries, null, NO_VISIBLE),
      { initialProps: { content: CONTENT } }
    );
    act(() => result.current.requestAiTitles(entries));
    rerender({ content: CONTENT + '\n新增' });
    await act(async () => {
      await vi.advanceTimersByTimeAsync(300);
    });
    await act(async () => {
      d.resolve({ ok: true, text: '[{"line":1,"title":"过期"}]' });
      await vi.advanceTimersByTimeAsync(0);
    });
    expect(result.current.aiStates[1]).not.toBe('loading');
  });

  it('过期请求抛错同样被丢弃', async () => {
    vi.useFakeTimers();
    const d = deferred<{ ok: boolean; text: string }>();
    setup({ 'ai-request': () => d.promise });
    const entries = [entry(1)];
    const { result, rerender } = renderHook(
      ({ content }) => useAiTitles(content, entries, null, NO_VISIBLE),
      { initialProps: { content: CONTENT } }
    );
    act(() => result.current.requestAiTitles(entries));
    rerender({ content: 'x' });
    await act(async () => {
      await vi.advanceTimersByTimeAsync(300);
    });
    await act(async () => {
      d.reject(new Error('late'));
      await vi.advanceTimersByTimeAsync(0);
    });
    expect(result.current.aiErrors).toEqual({});
  });
});

// ═══════════════════════════════════════════════════════════════════════════
// useAiSummaries
// ═══════════════════════════════════════════════════════════════════════════
describe('useAiSummaries', () => {
  const CONTENT = '第1章\n雪夜里林冲出走\n第2章\n追杀';
  const entries = [entry(1), entry(3)];
  const VIS = new Set<number>();

  it('请求摘要成功：清洗文本、写缓存并持久化', async () => {
    const { calls } = setup({
      'ai-request': () => ({ ok: true, text: '“林冲  雪夜出走。”' }),
    });
    const { result } = renderHook(() => useAiSummaries(CONTENT, entries, VIS));
    act(() => result.current.requestAiSummary(entries[0]));
    expect(result.current.aiSummaryStates).toEqual({ 1: 'loading' });
    await flush();
    expect(result.current.aiSummaryTexts).toEqual({ 1: '林冲 雪夜出走。' });
    expect(result.current.aiSummaryStates).toEqual({ 1: 'success' });
    expect(ctx.cache.summaryCache.get('k1')).toBe('林冲 雪夜出走。');
    expect(calls('ai-cache-set')).toEqual([['k1', 'summary', '林冲 雪夜出走。']]);
    const [payload] = calls('ai-request')[0] as [{ context: string }];
    expect(payload.context).toContain('雪夜里林冲出走');
    // 已成功后再次请求被忽略
    act(() => result.current.requestAiSummary(entries[0]));
    expect(calls('ai-request')).toHaveLength(1);
  });

  it('缓存命中时不请求', async () => {
    ctx.cache.summaryCache.set('k1', '缓存摘要');
    const { calls } = setup();
    const { result } = renderHook(() => useAiSummaries(CONTENT, entries, VIS));
    await flush();
    expect(result.current.aiSummaryTexts).toEqual({ 1: '缓存摘要' });
    expect(result.current.aiSummaryStates).toEqual({ 1: 'success' });
    act(() => result.current.requestAiSummary(entries[0]));
    expect(calls('ai-request')).toHaveLength(0);
  });

  it('无可用正文摘要时直接报错', async () => {
    const { calls } = setup();
    const { result } = renderHook(() => useAiSummaries(CONTENT, entries, VIS));
    act(() => result.current.requestAiSummary(entry(5, { summary: '暂无内容摘要' })));
    await flush();
    expect(calls('ai-request')).toHaveLength(0);
  });

  it('AI 未开启时不请求', async () => {
    ctx.aiReady = false;
    const { calls } = setup();
    const { result } = renderHook(() => useAiSummaries(CONTENT, entries, VIS));
    act(() => result.current.requestAiSummary(entries[0]));
    await flush();
    expect(calls('ai-request')).toHaveLength(0);
  });

  it('ok:false / 空文本 / 抛错 均进入错误状态', async () => {
    let mode: 'fail' | 'failNoMsg' | 'empty' | 'throw' | 'throwRaw' = 'fail';
    setup({
      'ai-request': () => {
        if (mode === 'throw') throw new Error('断网');
        if (mode === 'throwRaw') throw 1;
        if (mode === 'empty') return { ok: true, text: '“”' };
        if (mode === 'failNoMsg') return { ok: false };
        return { ok: false, error: '限流' };
      },
    });
    const { result } = renderHook(() => useAiSummaries(CONTENT, entries, VIS));
    const run = async (m: typeof mode) => {
      mode = m;
      act(() => result.current.refreshSummary(entries[0]));
      await flush();
      return result.current.aiSummaryErrors[1];
    };
    act(() => result.current.requestAiSummary(entries[0]));
    await flush();
    expect(result.current.aiSummaryStates).toEqual({ 1: 'error' });
    expect(result.current.aiSummaryErrors).toEqual({ 1: '限流' });
    expect(await run('failNoMsg')).toBe('AI 总结失败');
    expect(await run('empty')).toBe('AI 未返回可用总结');
    expect(await run('throw')).toBe('断网');
    expect(await run('throwRaw')).toBe('AI 总结失败');
    // error 状态下 requestAiSummary 允许重试
    mode = 'fail';
    act(() => result.current.requestAiSummary(entries[0]));
    await flush();
    expect(result.current.aiSummaryErrors[1]).toBe('限流');
  });

  it('refreshSummary 清除缓存并重新请求', async () => {
    ctx.cache.summaryCache.set('k1', '旧摘要');
    const { calls } = setup({ 'ai-request': () => ({ ok: true, text: '新摘要' }) });
    const { result } = renderHook(() => useAiSummaries(CONTENT, entries, VIS));
    await flush();
    act(() => result.current.refreshSummary(entries[0]));
    expect(calls('ai-cache-delete')).toEqual([['k1', 'summary']]);
    await flush();
    expect(result.current.aiSummaryTexts).toEqual({ 1: '新摘要' });
  });

  it('并发上限为 2，排队中的重复条目被忽略', async () => {
    const pending: Array<Deferred<{ ok: boolean; text: string }>> = [];
    const { calls } = setup({
      'ai-request': () => {
        const d = deferred<{ ok: boolean; text: string }>();
        pending.push(d);
        return d.promise;
      },
    });
    const many = [entry(1), entry(2), entry(3), entry(4)];
    const { result } = renderHook(() => useAiSummaries(CONTENT, many, VIS));
    act(() => {
      many.forEach((e) => result.current.requestAiSummary(e));
      result.current.requestAiSummary(many[3]);
    });
    await flush();
    expect(calls('ai-request')).toHaveLength(2);
    await act(async () => {
      pending[0].resolve({ ok: true, text: 'a' });
      pending[1].resolve({ ok: true, text: 'b' });
    });
    await flush();
    expect(calls('ai-request')).toHaveLength(4);
  });

  it('正文变化后过期响应被丢弃', async () => {
    vi.useFakeTimers();
    const d = deferred<{ ok: boolean; text: string }>();
    setup({ 'ai-request': () => d.promise });
    const { result, rerender } = renderHook(
      ({ content }) => useAiSummaries(content, entries, VIS),
      { initialProps: { content: CONTENT } }
    );
    act(() => result.current.requestAiSummary(entries[0]));
    rerender({ content: CONTENT + '!' });
    await act(async () => {
      await vi.advanceTimersByTimeAsync(300);
    });
    await act(async () => {
      d.resolve({ ok: true, text: '过期摘要' });
      await vi.advanceTimersByTimeAsync(0);
    });
    expect(result.current.aiSummaryTexts).toEqual({});
    expect(ctx.cache.summaryCache.size).toBe(0);
  });

  // BUG: useAiSummaries.ts runSummary 在过期分支（generation 不一致）直接 return，
  // 没有把之前设置的 'loading' 复位。正文变化后该条目永久处于 'loading'，
  // 而 requestAiSummary 对 'loading' 状态直接 return，悬浮再也无法重新请求摘要。
  it('BUG: 过期响应被丢弃后应能重新请求摘要', async () => {
    vi.useFakeTimers();
    const first = deferred<{ ok: boolean; text: string }>();
    let call = 0;
    const { calls } = setup({
      'ai-request': () => {
        call += 1;
        return call === 1 ? first.promise : { ok: true, text: '新摘要' };
      },
    });
    const { result, rerender } = renderHook(
      ({ content }) => useAiSummaries(content, entries, VIS),
      { initialProps: { content: CONTENT } }
    );
    act(() => result.current.requestAiSummary(entries[0]));
    rerender({ content: CONTENT + '!' });
    await act(async () => {
      await vi.advanceTimersByTimeAsync(300);
    });
    await act(async () => {
      first.resolve({ ok: true, text: '过期' });
      await vi.advanceTimersByTimeAsync(0);
    });
    act(() => result.current.requestAiSummary(entries[0]));
    await act(async () => {
      await vi.advanceTimersByTimeAsync(0);
    });
    expect(calls('ai-request')).toHaveLength(2);
  });

  it('缓存晚于挂载就绪时，恢复已缓存的摘要并清除错误', async () => {
    ctx.cache.cacheReady = false;
    setup({ 'ai-request': () => ({ ok: false, error: 'x' }) });
    const { result, rerender } = renderHook(() => useAiSummaries(CONTENT, entries, VIS));
    act(() => result.current.requestAiSummary(entries[1]));
    await flush();
    expect(result.current.aiSummaryErrors).toEqual({ 3: 'x' });
    ctx.cache.summaryCache.set('k3', '迟到的缓存');
    ctx.cache = { ...ctx.cache, cacheReady: true };
    rerender();
    await flush();
    expect(result.current.aiSummaryTexts).toEqual({ 3: '迟到的缓存' });
    expect(result.current.aiSummaryErrors).toEqual({});
    expect(result.current.aiSummaryStates[3]).toBe('success');
  });
});

// ═══════════════════════════════════════════════════════════════════════════
// useAiWorkflow 纯函数
// ═══════════════════════════════════════════════════════════════════════════
const REPORT = JSON.stringify({
  summary: '共 3 个问题',
  items: [
    {
      title: '称谓冲突',
      type: 'issue',
      severity: 'high',
      description: 'd1',
      impact: 'i',
      suggestion: 's',
    },
    { title: '节奏', type: 'custom', severity: 'medium', description: 'd2' },
    { title: '伏笔', severity: 'low', description: 'd3' },
    { title: '其他', description: 'd4' },
  ],
  conclusion: '整体可控',
});

describe('useAiWorkflow 工具函数', () => {
  it('tryParseJSON 支持代码块，拒绝无 items 与非法 JSON', () => {
    expect(tryParseJSON('```json\n' + REPORT + '\n```')?.items).toHaveLength(4);
    expect(tryParseJSON('{"summary":"x"}')).toBeNull();
    expect(tryParseJSON('not json')).toBeNull();
  });

  it('resultToMarkdown 渲染报告；非 JSON 原样返回', () => {
    const md = resultToMarkdown(REPORT, '一致性诊断');
    expect(md).toContain('# 一致性诊断 分析报告');
    expect(md).toContain('> 共 3 个问题');
    expect(md).toContain('## 1. 称谓冲突 [高]');
    expect(md).toContain('**类型**: 问题');
    expect(md).toContain('**类型**: custom');
    expect(md).toContain('## 2. 节奏 [中]');
    expect(md).toContain('## 3. 伏笔 [低]');
    expect(md).toContain('## 4. 其他\n');
    expect(md).toContain('**影响**: i');
    expect(md).toContain('**建议**: s');
    expect(md).toContain('## 总结\n\n整体可控');
    expect(resultToMarkdown('plain', 'x')).toBe('plain');
    expect(resultToMarkdown('{"items":[]}', 'x')).toBe('# x 分析报告\n');
  });

  it('getSeverityCounts 与 getHistorySummary', () => {
    expect(getSeverityCounts(REPORT)).toEqual({ high: 1, medium: 1, low: 1 });
    expect(getSeverityCounts('x')).toBeNull();
    expect(getHistorySummary(REPORT)).toBe('共 3 个问题');
    expect(getHistorySummary('{"items":[],"conclusion":"c"}')).toBe('c');
    expect(getHistorySummary('{"items":[{"title":"t","description":""}]}')).toBe('t');
    expect(getHistorySummary('{"items":[]}')).toBe('分析完成');
    expect(getHistorySummary('a'.repeat(100))).toHaveLength(80);
  });
});

// ═══════════════════════════════════════════════════════════════════════════
// useAiWorkflow hook
// ═══════════════════════════════════════════════════════════════════════════
describe('useAiWorkflow', () => {
  const FOLDER = '/novel';
  const SOURCE = '林冲在雪夜出走。\n他拔出长枪。';
  const ITEM: AIResultItem = { title: '称谓', description: '称谓不统一', suggestion: '统一' };

  function setupWorkflow(routes: Record<string, Handler> = {}) {
    return setup({
      'db-world-setting-list-by-folder': () => [
        {
          id: 1,
          category: 'world',
          title: '宋',
          content: '北宋末年',
          tags: '[]',
          created_at: '',
          updated_at: '',
        },
      ],
      'db-novel-get-by-folder': () => ({ id: 7 }),
      'db-character-list': () => [
        { id: 1, name: '林冲', role: '主角', description: '教头' },
        { id: 2, name: '高俅', role: '', description: '' },
      ],
      ...routes,
    });
  }

  type Opts = Parameters<typeof useAiWorkflow>[0];
  function renderWorkflow(overrides: Partial<Opts> = {}) {
    const addRecord = vi.fn();
    const hook = renderHook(
      (props: Partial<Opts>) =>
        useAiWorkflow({ folderPath: FOLDER, content: SOURCE, addRecord, ...overrides, ...props }),
      { initialProps: {} }
    );
    return { ...hook, addRecord };
  }

  it('加载设定与人物数量；无项目时为 0', async () => {
    setupWorkflow();
    const { result } = renderWorkflow();
    await flush();
    expect(result.current.contextCounts).toEqual({ lore: 1, characters: 2 });
    const none = renderWorkflow({ folderPath: null });
    await flush();
    expect(none.result.current.contextCounts).toEqual({ lore: 0, characters: 0 });
  });

  it('项目无 novel 记录时人物数为 0', async () => {
    setupWorkflow({ 'db-novel-get-by-folder': () => null });
    const { result } = renderWorkflow();
    await flush();
    expect(result.current.contextCounts).toEqual({ lore: 1, characters: 0 });
  });

  it('runAI 组装上下文、写入结果与历史记录', async () => {
    const { calls } = setupWorkflow({ 'ai-request': () => ({ ok: true, text: REPORT }) });
    const { result, addRecord } = renderWorkflow({ filePath: '/novel/a.md' });
    await flush();
    act(() => result.current.setPrompt('检查'));
    await act(async () => {
      await result.current.runAI();
    });
    const [payload] = calls('ai-request')[0] as [
      { prompt: string; systemPrompt: string; context: string },
    ];
    expect(payload.prompt.startsWith('检查')).toBe(true);
    expect(payload.context).toContain('正文片段:\n林冲在雪夜出走');
    expect(payload.context).toContain('设定集:\n宋: 北宋末年');
    expect(payload.context).toContain('林冲(主角): 教头');
    expect(payload.context).toContain('高俅(未设定): 无描述');
    expect(result.current.result).toBe(REPORT);
    expect(result.current.loading).toBe(false);
    expect(result.current.snapshotFilePath).toBe('/novel/a.md');
    expect(addRecord).toHaveBeenCalledWith(
      expect.objectContaining({
        workflow: 'consistency',
        prompt: '检查',
        result: REPORT,
        filePath: '/novel/a.md',
      })
    );
  });

  it('runAI：空 prompt 不请求；失败不写历史；异常写错误文本', async () => {
    let mode: 'fail' | 'failNoMsg' | 'empty' | 'throw' | 'throwRaw' = 'fail';
    const { calls } = setupWorkflow({
      'ai-request': () => {
        if (mode === 'throw') throw new Error('网络中断');
        if (mode === 'throwRaw') throw 0;
        if (mode === 'empty') return { ok: true };
        if (mode === 'failNoMsg') return { ok: false };
        return { ok: false, error: '额度不足' };
      },
    });
    const { result, addRecord } = renderWorkflow();
    await act(async () => {
      await result.current.runAI('   ');
    });
    expect(calls('ai-request')).toHaveLength(0);
    const run = async (m: typeof mode) => {
      mode = m;
      await act(async () => {
        await result.current.runAI('检查');
      });
      return result.current.result;
    };
    expect(await run('fail')).toBe('额度不足');
    expect(await run('failNoMsg')).toBe('AI 请求失败');
    expect(addRecord).not.toHaveBeenCalled();
    expect(await run('empty')).toBe('AI 未返回内容');
    expect(addRecord).toHaveBeenCalledTimes(1);
    expect(await run('throw')).toBe('网络中断');
    expect(await run('throwRaw')).toBe('AI 请求异常');
  });

  it('runAI：lore 工作流使用更长的正文切片；大文本走混合检索', async () => {
    const { calls } = setupWorkflow({ 'ai-request': () => ({ ok: true, text: 'x' }) });
    const longText = '甲'.repeat(9000);
    const { result, rerender } = renderWorkflow({ content: longText, folderPath: null });
    act(() => result.current.setWorkflow('lore'));
    await act(async () => {
      await result.current.runAI('补全');
    });
    const [p1] = calls('ai-request')[0] as [{ context: string }];
    expect(p1.context.length).toBeGreaterThan(7000);
    expect(p1.context).not.toContain('人物资料');

    const huge = Array.from(
      { length: 200 },
      (_, i) => `第${i + 1}章 标题\n${'乙'.repeat(400)}`
    ).join('\n');
    rerender({ content: huge });
    await act(async () => {
      await result.current.runAI('补全');
    });
    const [p2] = calls('ai-request')[1] as [{ context: string }];
    expect(p2.context.startsWith('正文片段:')).toBe(true);
    expect(p2.context.length).toBeLessThanOrEqual(12000 + 100);
  });

  it('handleCopy 复制 markdown 并在 2s 后复位', async () => {
    vi.useFakeTimers();
    setupWorkflow();
    const writeText = vi.fn(async () => {});
    Object.defineProperty(navigator, 'clipboard', { value: { writeText }, configurable: true });
    const { result } = renderWorkflow();
    act(() => result.current.handleCopy());
    expect(writeText).not.toHaveBeenCalled();
    act(() => result.current.setResult(REPORT));
    await act(async () => {
      result.current.handleCopy();
      await Promise.resolve();
    });
    expect(writeText.mock.calls[0][0]).toContain('# 一致性诊断 分析报告');
    expect(result.current.copied).toBe(true);
    await act(async () => {
      result.current.handleCopy();
      await Promise.resolve();
    });
    act(() => {
      vi.advanceTimersByTime(2000);
    });
    expect(result.current.copied).toBe(false);
  });

  it('handleSave 保存到 ai-reports；失败时回退剪贴板；success=false 不标记', async () => {
    vi.useFakeTimers();
    let mode: 'ok' | 'notOk' | 'throw' = 'ok';
    const { calls } = setupWorkflow({
      'save-analysis-file': () => {
        if (mode === 'throw') throw new Error('disk');
        return { success: mode === 'ok' };
      },
    });
    const writeText = vi.fn(async () => {});
    Object.defineProperty(navigator, 'clipboard', { value: { writeText }, configurable: true });
    const { result } = renderWorkflow();
    await act(async () => {
      await result.current.handleSave();
    });
    expect(calls('save-analysis-file')).toHaveLength(0);
    act(() => result.current.setResult(REPORT));
    await act(async () => {
      await result.current.handleSave();
    });
    const [folder, fileName, md] = calls('save-analysis-file')[0] as [string, string, string];
    expect(folder).toBe(FOLDER);
    expect(fileName).toMatch(/^AI分析_一致性诊断_\d{8}_\d{4}\.md$/);
    expect(md).toContain('分析报告');
    expect(result.current.saved).toBe(true);
    await act(async () => {
      await result.current.handleSave();
    });
    act(() => {
      vi.advanceTimersByTime(3000);
    });
    expect(result.current.saved).toBe(false);

    mode = 'notOk';
    await act(async () => {
      await result.current.handleSave();
    });
    expect(result.current.saved).toBe(false);

    mode = 'throw';
    await act(async () => {
      await result.current.handleSave();
    });
    expect(writeText).toHaveBeenCalled();
    expect(result.current.saved).toBe(true);
    await act(async () => {
      await result.current.handleSave();
    });
    act(() => {
      vi.advanceTimersByTime(3000);
    });
    expect(result.current.saved).toBe(false);
  });

  it('handleAutoFix 从磁盘读取原文，解析 fenced JSON 并触发 diff 预览', async () => {
    const fix = {
      original: '林冲在雪夜出走。',
      modified: '林教头在雪夜出走。',
      explanation: '统一称谓',
    };
    const { calls } = setupWorkflow({
      'read-file': () => SOURCE,
      'ai-request': () => ({ ok: true, text: '```json\n' + JSON.stringify(fix) + '\n```' }),
    });
    const onOpenFile = vi.fn();
    const onPreviewDiff = vi.fn();
    const { result } = renderWorkflow({
      content: '',
      filePath: '/novel/a.md',
      onOpenFile,
      onPreviewDiff,
    });
    let out: Awaited<ReturnType<typeof result.current.handleAutoFix>> | null = null;
    await act(async () => {
      out = await result.current.handleAutoFix(ITEM);
    });
    expect(calls('read-file')[0]).toEqual(['/novel/a.md']);
    expect(onOpenFile).toHaveBeenCalledWith('/novel/a.md');
    expect(onPreviewDiff).toHaveBeenCalledWith(fix.original, fix.modified);
    expect(out).toEqual({
      text: '统一称谓\n\n修改后：\n林教头在雪夜出走。',
      original: fix.original,
      modified: fix.modified,
    });
  });

  it('handleAutoFix：无 explanation / 非 JSON / 缺字段 / 失败 / 抛错', async () => {
    let response: unknown = { ok: true, text: '{"original":"林冲","modified":"林教头"}' };
    setupWorkflow({
      'read-file': () => {
        throw new Error('ENOENT');
      },
      'ai-request': () => {
        if (response instanceof Error) throw response;
        if (response === 'raw') throw 'raw';
        return response;
      },
    });
    const { result } = renderWorkflow({ filePath: '/novel/missing.md' });
    const run = async () => {
      let out: { text: string } = { text: '' };
      await act(async () => {
        out = await result.current.handleAutoFix(ITEM);
      });
      return out;
    };
    expect(await run()).toEqual({ text: '林教头', original: '林冲', modified: '林教头' });
    response = { ok: true, text: '直接改成林教头' };
    expect(await run()).toEqual({ text: '直接改成林教头' });
    response = { ok: true, text: '{"original":"林冲"}' };
    expect(await run()).toEqual({ text: '{"original":"林冲"}' });
    response = { ok: false, error: '限流' };
    expect(await run()).toEqual({ text: '限流' });
    response = { ok: false };
    expect(await run()).toEqual({ text: '自动修改失败' });
    response = new Error('超时');
    expect(await run()).toEqual({ text: '超时' });
    response = 'raw';
    expect(await run()).toEqual({ text: '自动修改异常' });
  });

  it('handleAutoFix：没有任何可用内容时提示打开文件；IPC 不可用时报错', async () => {
    setupWorkflow();
    const { result } = renderWorkflow({ content: '', filePath: '__untitled__' });
    let out: { text: string } = { text: '' };
    await act(async () => {
      out = await result.current.handleAutoFix(ITEM);
    });
    expect(out.text).toContain('未找到关联文件内容');
    uninstallElectronMock();
    await act(async () => {
      out = await result.current.handleAutoFix(ITEM);
    });
    expect(out).toEqual({ text: '无法连接 IPC' });
  });

  it('handleAutoFix 回退到 runAI 时的正文快照', async () => {
    const { calls } = setupWorkflow({ 'ai-request': () => ({ ok: true, text: 'r' }) });
    const { result, rerender } = renderWorkflow({ content: SOURCE });
    await act(async () => {
      await result.current.runAI('检查');
    });
    rerender({ content: '' });
    await act(async () => {
      await result.current.handleAutoFix(ITEM);
    });
    const [payload] = calls('ai-request')[1] as [{ context: string }];
    expect(payload.context).toContain('林冲在雪夜出走');
  });

  it('saveFixResult / removeFixResult', () => {
    setupWorkflow();
    const { result } = renderWorkflow();
    act(() => result.current.saveFixResult(0, { text: 'a' }));
    act(() => result.current.saveFixResult(2, { text: 'b' }));
    expect(Object.keys(result.current.fixResults)).toEqual(['0', '2']);
    act(() => result.current.removeFixResult(0));
    const before = result.current.fixResults;
    act(() => result.current.removeFixResult(9));
    expect(result.current.fixResults).toBe(before);
    expect(Object.keys(result.current.fixResults)).toEqual(['2']);
  });

  it('handleApplyFixToSource 主窗口模式：打开文件并回调 onApplyFix（含目标行）', async () => {
    setupWorkflow({ 'read-file': () => SOURCE });
    const onApplyFix = vi.fn();
    const onOpenFile = vi.fn();
    const { result } = renderWorkflow({ filePath: '/novel/a.md', onApplyFix, onOpenFile });
    await act(async () => {
      await result.current.handleApplyFixToSource({
        text: 't',
        original: '他拔出长枪。',
        modified: '他拔出了长枪。',
      });
    });
    expect(onOpenFile).toHaveBeenCalledWith('/novel/a.md');
    expect(onApplyFix).toHaveBeenCalledWith('他拔出长枪。', '他拔出了长枪。', '/novel/a.md', 2);
  });

  it('handleApplyFixToSource 独立窗口模式：委托给主窗口并附带完整内容', async () => {
    setupWorkflow({ 'read-file': () => SOURCE });
    const onDelegateFix = vi.fn();
    const onApplyFix = vi.fn();
    const { result } = renderWorkflow({
      filePath: '/novel/a.md',
      skipDiskWrite: true,
      onDelegateFix,
      onApplyFix,
    });
    await act(async () => {
      await result.current.handleApplyFixToSource({
        text: '说明\n\n修改后：\n林教头在雪夜出走。',
        original: '林冲在雪夜出走。',
        modified: '林教头在雪夜出走。',
      });
    });
    expect(onApplyFix).not.toHaveBeenCalled();
    expect(onDelegateFix).toHaveBeenCalledWith({
      filePath: '/novel/a.md',
      original: '林冲在雪夜出走。',
      modified: '林教头在雪夜出走。',
      explanation: '说明',
      proposedFullContent: '林教头在雪夜出走。\n他拔出长枪。',
      targetLine: 1,
    });
    await act(async () => {
      await result.current.handleApplyFixToSource({ text: 'm', original: '林冲', modified: 'm' });
    });
    expect(onDelegateFix.mock.calls[1][0].explanation).toBeUndefined();
  });

  it('handleApplyFixToSource：字段缺失忽略；原文找不到时抛出诊断错误；无内容时直接返回', async () => {
    setupWorkflow({
      'read-file': () => {
        throw new Error('x');
      },
    });
    const onApplyFix = vi.fn();
    const { result } = renderWorkflow({ filePath: '/novel/a.md', onApplyFix });
    await act(async () => {
      await result.current.handleApplyFixToSource({ text: 't' });
    });
    await act(async () => {
      await expect(
        result.current.handleApplyFixToSource({
          text: 't',
          original: '完全不存在的一段非常长的原文内容，用来确保匹配失败',
          modified: 'x',
        })
      ).rejects.toThrow('自动修复命中失败');
    });
    expect(onApplyFix).not.toHaveBeenCalled();

    const empty = renderWorkflow({ content: '', filePath: null, onApplyFix });
    await act(async () => {
      await empty.result.current.handleApplyFixToSource({
        text: 't',
        original: 'a',
        modified: 'b',
      });
    });
    expect(onApplyFix).not.toHaveBeenCalled();
  });

  it('卸载时清理计时器', async () => {
    vi.useFakeTimers();
    setupWorkflow();
    const writeText = vi.fn(async () => {});
    Object.defineProperty(navigator, 'clipboard', { value: { writeText }, configurable: true });
    const clear = vi.spyOn(window, 'clearTimeout');
    const { result, unmount } = renderWorkflow();
    act(() => result.current.setResult(REPORT));
    await act(async () => {
      result.current.handleCopy();
      await Promise.resolve();
    });
    await act(async () => {
      await result.current.handleSave();
    });
    unmount();
    expect(clear).toHaveBeenCalled();
  });
});
