// @vitest-environment happy-dom
import React from 'react';
import { afterEach, beforeEach, describe, expect, it, vi } from 'vitest';
import { act, fireEvent, render, screen } from '@testing-library/react';
import type { OutlineEntry } from '@/render/components/RightPanel/types';

// ─── 受控的 hook 状态（每个用例在 beforeEach 中重置） ─────────────────────
const h = vi.hoisted(() => {
  const fn = () => vi.fn();
  return {
    outline: {} as Record<string, unknown>,
    titles: {} as Record<string, unknown>,
    summaries: {} as Record<string, unknown>,
    aiConfig: { loaded: true, ready: true } as { loaded: boolean; ready: boolean },
    versionCenter: {} as Record<string, unknown>,
    fn,
  };
});

vi.mock('@/render/components/RightPanel/useOutlineEntries', () => ({
  useOutlineEntries: () => h.outline,
}));
vi.mock('@/render/components/RightPanel/useAiTitles', () => ({
  useAiTitles: () => h.titles,
}));
vi.mock('@/render/components/RightPanel/useAiSummaries', () => ({
  useAiSummaries: () => h.summaries,
}));
vi.mock('@/render/components/RightPanel/useAiConfig', () => ({
  useAiConfig: () => h.aiConfig,
}));
vi.mock('@/render/components/Dialog', () => ({
  useDialog: () => ({}),
}));
vi.mock('@/render/components/RightPanel/OutlineView/useOutlineVersionCenter', () => ({
  useOutlineVersionCenter: () => h.versionCenter,
}));
vi.mock('@/render/components/RightPanel/OutlineView/OutlineVersionsPanel', () => ({
  OutlineVersionsPanel: ({ versions }: { versions: unknown[] }) => (
    <div data-testid="versions-panel">versions:{versions.length}</div>
  ),
}));
vi.mock('@/render/components/RightPanel/OutlineView/OutlineAiPresetPanel', () => ({
  OutlineAiPresetPanel: ({ aiOptionsLabel }: { aiOptionsLabel: string }) => (
    <div data-testid="ai-preset-panel">{aiOptionsLabel}</div>
  ),
}));
vi.mock('@/render/components/RightPanel/OutlinePopover', () => ({
  OutlinePopover: ({
    entry,
    summaryText,
    summaryState,
  }: {
    entry: OutlineEntry | null;
    summaryText: string;
    summaryState: string;
  }) =>
    entry ? (
      <div data-testid="popover">
        {entry.text}|{summaryText}|{summaryState}
      </div>
    ) : null,
}));

import { OutlineView } from '@/render/components/RightPanel/OutlineView';

// ─── IntersectionObserver stub（可手动触发） ─────────────────────────────
type IOCallback = (entries: Array<{ target: Element; isIntersecting: boolean }>) => void;
const observers: Array<{ cb: IOCallback; targets: Element[] }> = [];
class FakeIO {
  private record: { cb: IOCallback; targets: Element[] };
  constructor(cb: IOCallback) {
    this.record = { cb, targets: [] };
    observers.push(this.record);
  }
  observe(el: Element) {
    this.record.targets.push(el);
  }
  disconnect() {
    this.record.targets = [];
  }
}

const entry = (line: number, text: string, extra: Partial<OutlineEntry> = {}): OutlineEntry => ({
  cacheKey: `k-${line}`,
  line,
  level: 1,
  text,
  summary: '',
  autoGenerated: false,
  source: 'document',
  wordCount: 100,
  ...extra,
});

const liveEntries = [
  entry(1, '第一章', { needsAiTitle: true }),
  entry(10, '第二章', { needsAiTitle: true, wordCount: 20000 }),
  entry(20, '第三章'),
];
const dbEntries = [
  entry(1, '序幕', { source: 'database', lineHint: 5, anchorText: '锚点', summary: '库内摘要' }),
  entry(2, '高潮', { source: 'database', lineHint: 0 }),
];

beforeEach(() => {
  observers.length = 0;
  vi.stubGlobal('IntersectionObserver', FakeIO);
  h.aiConfig = { loaded: true, ready: true };
  h.outline = {
    liveEntries,
    persistedEntries: dbEntries,
    versions: [],
    hasPersistedOutline: true,
    loading: false,
    importing: false,
    statusMessage: '',
    importOutline: vi.fn(),
    rebuildFromContent: vi.fn(),
    clearPersisted: vi.fn(),
    saveOutlineVersion: vi.fn(),
    applyOutlineVersion: vi.fn(),
    updateOutlineVersion: vi.fn(),
    deleteOutlineVersion: vi.fn(),
    generateAiOutline: vi.fn(async () => undefined),
    reorderEntries: vi.fn(async () => undefined),
  };
  h.titles = {
    aiTitles: {} as Record<number, string>,
    aiStates: {} as Record<number, string>,
    aiErrors: {},
    failedAiEntries: [],
    retryAiEntry: vi.fn(),
    retryFailedEntries: vi.fn(),
  };
  h.summaries = {
    aiSummaryTexts: {} as Record<number, string>,
    aiSummaryStates: {} as Record<number, string>,
    aiSummaryErrors: {} as Record<number, string>,
    requestAiSummary: vi.fn(),
    refreshSummary: vi.fn(),
  };
  h.versionCenter = {
    compareBaseVersionId: null,
    compareTargetVersionId: null,
    highlightedStoryIdeaVersionId: null,
    handleSaveVersion: vi.fn(),
    handleApplyVersion: vi.fn(),
    handleEditVersion: vi.fn(),
    handleDeleteVersion: vi.fn(),
    handleSetCompareBase: vi.fn(),
    handleSetCompareTarget: vi.fn(),
    previewData: null,
  };
});

afterEach(() => {
  vi.unstubAllGlobals();
  vi.useRealTimers();
});

type Props = React.ComponentProps<typeof OutlineView>;
const renderView = (props: Partial<Props> = {}) =>
  render(<OutlineView mode="catalog" content="正文" folderPath="/novel" dbReady {...props} />);

describe('OutlineView', () => {
  it('目录模式：无内容时空提示', () => {
    renderView({ content: '' });
    expect(screen.getByText('打开文件后查看目录')).toBeTruthy();
  });

  it('目录模式：无标题时提示', () => {
    h.outline.liveEntries = [];
    renderView();
    expect(screen.getByText(/未检测到标题结构/)).toBeTruthy();
  });

  it('目录模式：渲染统计与节点，点击定位', () => {
    const onScrollToLine = vi.fn();
    renderView({ onScrollToLine });
    expect(screen.getByText('3 节点')).toBeTruthy();
    expect(screen.getByText('2.0 万字')).toBeTruthy();
    expect(screen.getByText('目录（实时）')).toBeTruthy();
    expect(screen.queryByText('导入大纲')).toBeNull();
    fireEvent.click(screen.getByText('第二章'));
    expect(onScrollToLine).toHaveBeenCalledWith(10, '第二章');
  });

  it('目录模式：AI 标题进度、应用标题、失败重试', () => {
    (h.titles.aiTitles as Record<number, string>)[1] = '风起';
    (h.titles.aiStates as Record<number, string>)[10] = 'error';
    h.titles.failedAiEntries = [liveEntries[1]];
    const onReplaceLineText = vi.fn();
    renderView({ onReplaceLineText });
    expect(screen.getByText('AI 1/2')).toBeTruthy();
    fireEvent.click(screen.getByRole('button', { name: '应用' }));
    expect(onReplaceLineText).toHaveBeenCalledWith(1, '风起');
    expect(screen.getByText('已应用')).toBeTruthy();

    fireEvent.click(screen.getByRole('button', { name: '重试失败项 (1)' }));
    expect(h.titles.retryFailedEntries).toHaveBeenCalled();
    fireEvent.click(screen.getByRole('button', { name: '重试' }));
    expect(h.titles.retryAiEntry).toHaveBeenCalledWith(liveEntries[1]);
  });

  it('AI 未就绪时显示"开启 AI"并派发打开设置事件', () => {
    h.aiConfig = { loaded: true, ready: false };
    const listener = vi.fn();
    window.addEventListener('open-settings-tab', listener);
    renderView({ content: '正文内容' });
    fireEvent.click(screen.getByText('开启 AI'));
    expect(listener).toHaveBeenCalled();
    expect((listener.mock.calls[0][0] as CustomEvent).detail).toBe('ai');
    window.removeEventListener('open-settings-tab', listener);
  });

  it('加载中 / 处理中 / 状态消息', () => {
    h.outline.loading = true;
    h.outline.importing = true;
    h.outline.statusMessage = '已导入 3 个节点';
    renderView();
    expect(screen.getByText('加载中...')).toBeTruthy();
    expect(screen.getByText('处理中...')).toBeTruthy();
    expect(screen.getByText('已导入 3 个节点')).toBeTruthy();
  });

  it('悬停：请求摘要、显示 popover、延迟隐藏', () => {
    vi.useFakeTimers();
    (h.summaries.aiSummaryTexts as Record<number, string>)[1] = 'AI 摘要';
    renderView();
    const node = screen.getByText('第一章').closest('[class*="outlineNode"]') as HTMLElement;
    fireEvent.mouseEnter(node);
    expect(h.summaries.requestAiSummary).toHaveBeenCalledWith(liveEntries[0]);
    expect(screen.getByTestId('popover').textContent).toBe('第一章|AI 摘要|success');
    fireEvent.mouseLeave(node);
    act(() => {
      vi.advanceTimersByTime(300);
    });
    expect(screen.queryByTestId('popover')).toBeNull();
  });

  it('悬停：摘要失败时不显示 popover（tooltip-only）', () => {
    (h.summaries.aiSummaryStates as Record<number, string>)[1] = 'error';
    (h.summaries.aiSummaryErrors as Record<number, string>)[1] = '摘要失败';
    renderView();
    const node = screen.getByText('第一章').closest('[class*="outlineNode"]') as HTMLElement;
    fireEvent.mouseEnter(node);
    expect(screen.queryByTestId('popover')).toBeNull();
  });

  it('悬停后摘要转为失败时自动关闭 popover', () => {
    const { rerender } = renderView();
    const node = screen.getByText('第一章').closest('[class*="outlineNode"]') as HTMLElement;
    fireEvent.mouseEnter(node);
    expect(screen.getByTestId('popover')).toBeTruthy();
    h.summaries = {
      ...h.summaries,
      aiSummaryStates: { 1: 'error' },
    };
    // memo 组件：换一个回调 prop 触发重渲染（content 不变）
    rerender(
      <OutlineView
        mode="catalog"
        content="正文"
        folderPath="/novel"
        dbReady
        onScrollToLine={() => undefined}
      />
    );
    expect(screen.queryByTestId('popover')).toBeNull();
  });

  it('IntersectionObserver 记录可见行', () => {
    renderView();
    const record = observers.at(-1);
    expect(record?.targets.length).toBe(3);
    act(() => {
      record?.cb([
        { target: record.targets[0], isIntersecting: true },
        { target: record.targets[1], isIntersecting: false },
        { target: document.createElement('div'), isIntersecting: true },
      ]);
    });
    act(() => {
      record?.cb([{ target: record.targets[0], isIntersecting: false }]);
    });
    expect(screen.getByText('3 节点')).toBeTruthy();
  });

  it('大纲模式：空状态（作品/章节范围）与工具栏', () => {
    h.outline.persistedEntries = [];
    h.outline.hasPersistedOutline = false;
    h.outline.versions = [{ id: 1 }];
    h.outline.statusMessage = '没有可导入内容';
    const { unmount } = render(
      <OutlineView mode="outline" content="正文" folderPath="/novel" dbReady scopeLabel="我的书" />
    );
    expect(screen.getByText(/暂无入库作品大纲/)).toBeTruthy();
    expect(screen.getByText('可为「我的书」导入、生成或重建独立作品大纲')).toBeTruthy();
    expect(screen.getByText('没有可导入内容')).toBeTruthy();
    expect(screen.getByTestId('versions-panel').textContent).toBe('versions:1');

    fireEvent.click(screen.getByRole('button', { name: '导入大纲' }));
    expect(h.outline.importOutline).toHaveBeenCalled();
    fireEvent.click(screen.getByRole('button', { name: '从正文重建' }));
    expect(h.outline.rebuildFromContent).toHaveBeenCalled();
    fireEvent.click(screen.getByRole('button', { name: 'AI 生成大纲' }));
    expect(h.outline.generateAiOutline).toHaveBeenCalledWith({
      style: 'balanced',
      granularity: 'medium',
      maxDepth: 3,
    });
    expect(
      (screen.getByRole('button', { name: '保存为大纲版本' }) as HTMLButtonElement).disabled
    ).toBe(true);
    fireEvent.click(screen.getByRole('button', { name: 'AI 预设' }));
    expect(screen.getByTestId('ai-preset-panel')).toBeTruthy();
    fireEvent.click(screen.getByRole('button', { name: '收起预设' }));
    expect(screen.queryByTestId('ai-preset-panel')).toBeNull();
    unmount();

    render(
      <OutlineView
        mode="outline"
        content=""
        folderPath={null}
        dbReady={false}
        scope={{ kind: 'chapter' } as Props['scope']}
        scopeLabel="第一章"
      />
    );
    expect(screen.getByText(/暂无入库章纲/)).toBeTruthy();
    expect(screen.getByText('可为「第一章」导入、生成或重建独立章纲')).toBeTruthy();
    expect((screen.getByRole('button', { name: '导入大纲' }) as HTMLButtonElement).disabled).toBe(
      true
    );
  });

  it('大纲模式：入库节点、工具栏操作、数据库节点定位', () => {
    const onScrollToLine = vi.fn();
    render(
      <OutlineView
        mode="outline"
        content="正文"
        folderPath="/novel"
        dbReady
        onScrollToLine={onScrollToLine}
      />
    );
    expect(screen.getByText('2 节点')).toBeTruthy();
    expect(screen.getByText('已入库作品大纲')).toBeTruthy();
    expect(screen.getByText(/^AI 生成：.+ \/ .+ \/ 3 层$/)).toBeTruthy();
    expect(screen.getByTestId('versions-panel')).toBeTruthy();

    fireEvent.click(screen.getByText('序幕'));
    expect(onScrollToLine).toHaveBeenCalledWith(5, '锚点');
    onScrollToLine.mockClear();
    fireEvent.click(screen.getByText('高潮'));
    expect(onScrollToLine).not.toHaveBeenCalled();

    fireEvent.click(screen.getByRole('button', { name: '导入大纲' }));
    fireEvent.click(screen.getByRole('button', { name: '从正文重建' }));
    fireEvent.click(screen.getByRole('button', { name: 'AI 生成大纲' }));
    fireEvent.click(screen.getByRole('button', { name: '保存为大纲版本' }));
    fireEvent.click(screen.getByRole('button', { name: '清空入库' }));
    fireEvent.click(screen.getByRole('button', { name: 'AI 预设' }));
    expect(h.outline.importOutline).toHaveBeenCalled();
    expect(h.outline.rebuildFromContent).toHaveBeenCalled();
    expect(h.outline.generateAiOutline).toHaveBeenCalled();
    expect(h.versionCenter.handleSaveVersion).toHaveBeenCalled();
    expect(h.outline.clearPersisted).toHaveBeenCalled();
    expect(screen.getByTestId('ai-preset-panel')).toBeTruthy();

    // 数据库条目悬停不请求 AI 摘要，popover 使用库内摘要
    const node = screen.getByText('序幕').closest('[class*="outlineNode"]') as HTMLElement;
    fireEvent.mouseEnter(node);
    expect(h.summaries.requestAiSummary).not.toHaveBeenCalled();
    expect(screen.getByTestId('popover').textContent).toBe('序幕|库内摘要|idle');
  });

  it('大纲模式：拖拽排序调用 reorderEntries', () => {
    render(<OutlineView mode="outline" content="正文" folderPath="/novel" dbReady />);
    const first = screen.getByText('序幕').closest('[draggable="true"]') as HTMLElement;
    const second = screen.getByText('高潮').closest('[draggable="true"]') as HTMLElement;
    fireEvent.dragStart(first, { dataTransfer: { effectAllowed: '' } });
    fireEvent.dragOver(second, { dataTransfer: { dropEffect: '' } });
    fireEvent.dragEnd(first);
    expect(h.outline.reorderEntries).toHaveBeenCalledWith(0, 1);

    // 同位置不触发
    (h.outline.reorderEntries as ReturnType<typeof vi.fn>).mockClear();
    fireEvent.dragStart(first, { dataTransfer: { effectAllowed: '' } });
    fireEvent.dragOver(first, { dataTransfer: { dropEffect: '' } });
    fireEvent.drop(first, { dataTransfer: {} });
    expect(h.outline.reorderEntries).not.toHaveBeenCalled();
  });
});
