import type { OutlineNode } from '@novel-editor/basic-algorithm';
import {
  CHARACTER_CATEGORY_LABELS,
  DEFAULT_CHARACTER_HIGHLIGHT_COLOR,
  buildCharacterLinks,
  buildOutlineCacheKeyFromTitle,
  buildOutlineEntries,
  buildOutlineEntryCacheKey,
  createCharacterTimelineOrderStorageKey,
  createCharacterTimelineStorageKey,
  createGraphLayoutStorageKey,
  createLoreStorageKey,
  createPlotStorageKey,
  createRelationStorageKey,
  escapeRegex,
  estimateAppearanceHeat,
  extractChapterContent,
  extractJsonBlock,
  extractLineSummary,
  fnv1a32,
  getCharacterTimelineOrderKey,
  getRoleColor,
  inferCharacterCamp,
  inferCharacterCategoryFromRole,
  inferRelationStage,
  isChapterHeading,
  isGenericOutlineTitle,
  mapCharacterRows,
  mergeCharacterGraphResults,
  mergeCharacterTimelineItems,
  migrateCacheKey,
  normalizeCharacterCategory,
  normalizePersonName,
  normalizeRelationTone,
  parseCharacterAttributes,
  parseCharacterGraphAIResult,
  parseCharacterTimelineItems,
  parseOutlineTitleCompletions,
  parseTimelineOrderKeys,
  sanitizeAiSummary,
  selectChapterHeadings,
  splitTextIntoChunks,
  stringifyCharacterAttributes,
} from '@/render/components/RightPanel/utils';
import type {
  Character,
  CharacterRelation,
  CharacterTimelineItem,
  OutlineEntry,
} from '@/render/components/RightPanel/types';

function makeEntry(overrides: Partial<OutlineEntry> = {}): OutlineEntry {
  return {
    cacheKey: '',
    line: 1,
    level: 1,
    text: '第一章 风起青萍',
    summary: '',
    autoGenerated: false,
    wordCount: 0,
    ...overrides,
  };
}

function makeCharacter(overrides: Partial<Character> = {}): Character {
  return {
    id: 1,
    name: '林远',
    role: '主角',
    category: 'major',
    description: '',
    currentState: [],
    ...overrides,
  };
}

function heading(text: string, line: number, level = 1): OutlineNode {
  return { text, line, level, source: 'chinese-section' };
}

function relation(
  sourceId: number,
  targetId: number,
  tone: CharacterRelation['tone']
): CharacterRelation {
  return { id: `${sourceId}-${targetId}-${tone}`, sourceId, targetId, label: '', tone, note: '' };
}

describe('fnv1a32 / cache keys', () => {
  it('matches known FNV-1a test vectors', () => {
    expect(fnv1a32('')).toBe('811c9dc5');
    expect(fnv1a32('a')).toBe('e40c292c');
    expect(fnv1a32('foobar')).toBe('bf9cf968');
  });

  it('always returns 8 lowercase hex chars and is deterministic', () => {
    const value = fnv1a32('第一章 风起青萍');
    expect(value).toMatch(/^[0-9a-f]{8}$/);
    expect(fnv1a32('第一章 风起青萍')).toBe(value);
    expect(fnv1a32('第二章 风起青萍')).not.toBe(value);
  });

  it('buildOutlineEntryCacheKey prefers cacheKey, then originalText, then text', () => {
    expect(buildOutlineEntryCacheKey(makeEntry({ cacheKey: 'abc' }))).toBe('abc');
    expect(buildOutlineEntryCacheKey(makeEntry({ originalText: '第一章', text: 'AI 标题' }))).toBe(
      fnv1a32('第一章')
    );
    expect(buildOutlineEntryCacheKey(makeEntry({ text: '第三章 夜袭' }))).toBe(
      fnv1a32('第三章 夜袭')
    );
  });

  it('buildOutlineCacheKeyFromTitle trims the title', () => {
    expect(buildOutlineCacheKeyFromTitle('  第一章  ')).toBe(fnv1a32('第一章'));
  });

  it('migrateCacheKey returns null for already-hashed keys', () => {
    expect(migrateCacheKey(fnv1a32('第一章'))).toBeNull();
  });

  it('migrateCacheKey hashes legacy raw titles and strips fingerprints', () => {
    expect(migrateCacheKey('第一章 风起')).toBe(fnv1a32('第一章 风起'));
    expect(migrateCacheKey('第一章 风起|fp-123|x')).toBe(fnv1a32('第一章 风起'));
    // uppercase hex is not considered migrated
    expect(migrateCacheKey('ABCDEF12')).toBe(fnv1a32('ABCDEF12'));
  });
});

describe('sanitizeAiSummary', () => {
  it('strips surrounding ASCII quotes and collapses whitespace', () => {
    expect(sanitizeAiSummary('"林远  初入\n青云宗"')).toBe('林远 初入 青云宗');
    expect(sanitizeAiSummary("'苏晴登场'")).toBe('苏晴登场');
    expect(sanitizeAiSummary('   ')).toBe('');
  });

  // 回归（已修复）：the regex character class is ['"""] — three ASCII double quotes. It was clearly meant to
  // contain Chinese curly quotes (“ ”) like typical AI output, so “...” is never stripped.
  it('strips Chinese curly quotes around AI summaries', () => {
    expect(sanitizeAiSummary('“林远初入青云宗”')).toBe('林远初入青云宗');
  });

  it('先去除首尾空白再剥引号，仅含引号与空白时返回空', () => {
    expect(sanitizeAiSummary('  ""  ')).toBe('');
    expect(sanitizeAiSummary('  “林远登场”\n')).toBe('林远登场');
  });
});

describe('storage key builders', () => {
  it('return null when there is no folder', () => {
    expect(createLoreStorageKey(null)).toBeNull();
    expect(createRelationStorageKey(null)).toBeNull();
    expect(createPlotStorageKey(null)).toBeNull();
    expect(createGraphLayoutStorageKey(null)).toBeNull();
    expect(createLoreStorageKey('')).toBeNull();
  });

  it('namespace by folder path', () => {
    const folder = '/Users/a/小说/青云志';
    expect(createLoreStorageKey(folder)).toBe(`novel-editor:lore:${folder}`);
    expect(createRelationStorageKey(folder)).toBe(`novel-editor:character-relations:${folder}`);
    expect(createPlotStorageKey(folder)).toBe(`novel-editor:plot-board:${folder}`);
    expect(createGraphLayoutStorageKey(folder)).toBe(`novel-editor:graph-layout:${folder}`);
  });

  it('timeline keys depend on novelId (0 is valid)', () => {
    expect(createCharacterTimelineStorageKey(null, 3)).toBeNull();
    expect(createCharacterTimelineStorageKey(0, 3)).toBe('novel-editor:character-timeline:0:3');
    expect(createCharacterTimelineOrderStorageKey(null, 3)).toBeNull();
    expect(createCharacterTimelineOrderStorageKey(7, 9)).toBe(
      'novel-editor:character-timeline-order:7:9'
    );
  });
});

describe('normalizePersonName / escapeRegex / estimateAppearanceHeat', () => {
  it('removes whitespace and lowercases', () => {
    expect(normalizePersonName(' 林 远 ')).toBe('林远');
    expect(normalizePersonName('Lin  Yuan')).toBe('linyuan');
  });

  it('escapes regex metacharacters', () => {
    expect(escapeRegex('a.b*c(d)[e]')).toBe('a\\.b\\*c\\(d\\)\\[e\\]');
    expect(new RegExp(escapeRegex('C++')).test('学 C++')).toBe(true);
  });

  it('counts name occurrences, safely with special chars', () => {
    const text = '林远看向苏晴。苏晴笑了，林远也笑了。林远转身离开。';
    expect(estimateAppearanceHeat(text, '林远')).toBe(3);
    expect(estimateAppearanceHeat(text, ' 苏晴 ')).toBe(2);
    expect(estimateAppearanceHeat(text, '赵无极')).toBe(0);
    expect(estimateAppearanceHeat(text, '   ')).toBe(0);
    expect(estimateAppearanceHeat('a.b ab a.b', 'a.b')).toBe(2);
  });
});

describe('splitTextIntoChunks', () => {
  it('returns [] for empty content', () => {
    expect(splitTextIntoChunks('', 100)).toEqual([]);
    expect(splitTextIntoChunks('  \n\n  ', 100)).toEqual([]);
  });

  it('packs paragraphs into chunks up to maxChars', () => {
    const content = '林远醒来。\n\n苏晴在门外。\n\n\n远处传来钟声。';
    expect(splitTextIntoChunks(content, 100)).toEqual([
      '林远醒来。\n\n苏晴在门外。\n\n远处传来钟声。',
    ]);
    expect(splitTextIntoChunks(content, 13)).toEqual([
      '林远醒来。\n\n苏晴在门外。',
      '远处传来钟声。',
    ]);
  });

  it('hard-splits paragraphs longer than maxChars', () => {
    const long = '剑'.repeat(25);
    const chunks = splitTextIntoChunks(`短段\n\n${long}\n\n尾声`, 10);
    expect(chunks).toEqual(['短段', '剑'.repeat(10), '剑'.repeat(10), '剑'.repeat(5), '尾声']);
  });
});

describe('extractJsonBlock', () => {
  it('extracts ```json fenced blocks', () => {
    expect(extractJsonBlock('好的：\n```json\n{"a":1}\n```\n以上')).toBe('{"a":1}');
  });

  it('extracts generic fenced blocks', () => {
    expect(extractJsonBlock('```\n[1,2]\n```')).toBe('[1,2]');
  });

  it('falls back to outermost braces', () => {
    expect(extractJsonBlock('结果是 {"name":"林远"} 完毕')).toBe('{"name":"林远"}');
  });

  it('returns null when nothing JSON-like exists', () => {
    expect(extractJsonBlock('没有 JSON')).toBeNull();
    expect(extractJsonBlock('} reversed {')).toBeNull();
  });

  it('extracts bare arrays, ignoring brackets inside strings and non-JSON brackets', () => {
    expect(extractJsonBlock('如下：[{"a":1},{"b":2}] 完')).toBe('[{"a":1},{"b":2}]');
    expect(extractJsonBlock('[{"t":"含 ] 与 } 的标题"}]')).toBe('[{"t":"含 ] 与 } 的标题"}]');
    expect(extractJsonBlock('结果[注]：{"name":"林远"}')).toBe('{"name":"林远"}');
    expect(extractJsonBlock('对象优先 {"list":[1,2]} 尾')).toBe('{"list":[1,2]}');
  });
});

describe('normalizeRelationTone', () => {
  it.each([
    ['ally', 'ally'],
    ['盟友', 'ally'],
    ['合作伙伴', 'ally'],
    ['RIVAL', 'rival'],
    ['对立', 'rival'],
    ['宿敌', 'rival'],
    ['family', 'family'],
    ['亲兄妹', 'family'],
    ['血缘', 'family'],
    ['mentor', 'mentor'],
    ['师徒', 'mentor'],
    ['引导者', 'mentor'],
    ['路人', 'other'],
    ['', 'other'],
  ])('%s -> %s', (input, expected) => {
    expect(normalizeRelationTone(input)).toBe(expected);
  });

  it('handles undefined', () => {
    expect(normalizeRelationTone(undefined)).toBe('other');
  });
});

describe('parseCharacterGraphAIResult', () => {
  it('parses characters/relations and drops nameless items', () => {
    const raw = `\`\`\`json
{
  "characters": [{"name":"林远","role":"主角"},{"name":"  "},{"role":"无名"}],
  "relations": [{"source":"林远","target":"苏晴","label":"恋人"},{"source":"林远","target":""}],
  "summary": "  两人初遇  "
}
\`\`\``;
    const result = parseCharacterGraphAIResult(raw);
    expect(result).toEqual({
      characters: [{ name: '林远', role: '主角' }],
      relations: [{ source: '林远', target: '苏晴', label: '恋人' }],
      summary: '两人初遇',
    });
  });

  it('accepts cast/links aliases and missing summary', () => {
    const result = parseCharacterGraphAIResult(
      '{"cast":[{"name":"苏晴"}],"links":[{"source":"苏晴","target":"林远"}]}'
    );
    expect(result?.characters).toHaveLength(1);
    expect(result?.relations).toHaveLength(1);
    expect(result?.summary).toBe('');
  });

  it('returns empty arrays when keys are missing', () => {
    expect(parseCharacterGraphAIResult('{"foo":1}')).toEqual({
      characters: [],
      relations: [],
      summary: '',
    });
  });

  it('returns null on missing or malformed JSON', () => {
    expect(parseCharacterGraphAIResult('no json')).toBeNull();
    expect(parseCharacterGraphAIResult('{bad json}')).toBeNull();
  });
});

describe('mergeCharacterGraphResults', () => {
  it('merges characters by normalized name/alias and dedups relations', () => {
    const merged = mergeCharacterGraphResults([
      {
        characters: [
          { name: '林远', role: '', description: '青云宗弟子', aliases: ['远哥'] },
          { name: '苏晴', role: '女主', description: '药王谷传人' },
        ],
        relations: [
          { source: '林远', target: '苏晴', label: '恋人', tone: 'ally' },
          { source: '林远', target: '林远', label: '自我' },
        ],
        summary: '第一段',
      },
      {
        characters: [
          {
            name: '远哥',
            role: '主角',
            description: '青云宗弟子',
            highlight: '剑心通明',
            aliases: ['林远', ' '],
          },
          { name: '  ', role: '无名' },
        ],
        relations: [
          { source: ' 林远 ', target: '苏晴', label: '恋人', tone: 'ally' },
          { source: '林远', target: '赵无极', tone: '宿敌', note: ' 血海深仇 ' },
        ],
        summary: '',
      },
      { characters: [], relations: [], summary: '第三段' },
      { characters: [], relations: [], summary: '第四段' },
      { characters: [], relations: [], summary: '第五段' },
    ]);

    expect(merged.characters).toEqual([
      {
        name: '林远',
        role: '主角',
        description: '青云宗弟子；剑心通明',
        aliases: ['远哥', '林远'],
      },
      { name: '苏晴', role: '女主', description: '药王谷传人', aliases: [] },
    ]);
    expect(merged.relations).toEqual([
      { source: '林远', target: '苏晴', label: '恋人', tone: 'ally', note: '' },
      { source: '林远', target: '赵无极', label: '对立', tone: 'rival', note: '血海深仇' },
    ]);
    expect(merged.summary).toBe('第一段 / 第三段 / 第四段');
  });

  it('keeps existing role when later chunk has none and truncates description', () => {
    const merged = mergeCharacterGraphResults([
      {
        characters: [{ name: '林远', role: '主角', description: '甲'.repeat(200) }],
        relations: [],
        summary: '',
      },
      {
        characters: [{ name: '林远', role: '  ', description: '乙'.repeat(200) }],
        relations: [],
        summary: '',
      },
    ]);
    expect(merged.characters[0].role).toBe('主角');
    expect(merged.characters[0].description).toHaveLength(280);
  });

  it('returns empty result for no input', () => {
    expect(mergeCharacterGraphResults([])).toEqual({ characters: [], relations: [], summary: '' });
  });

  // 回归（已修复）：aliases of already-merged characters are never indexed in characterMap, so a later
  // chunk mentioning the canonical name doesn't merge with an earlier entry that listed it as alias.
  it('merges a character whose name matches an earlier alias', () => {
    const merged = mergeCharacterGraphResults([
      { characters: [{ name: '远哥', aliases: ['林远'] }], relations: [], summary: '' },
      { characters: [{ name: '林远' }], relations: [], summary: '' },
    ]);
    expect(merged.characters).toHaveLength(1);
  });
});

describe('character category & attributes', () => {
  it('infers category from role', () => {
    expect(inferCharacterCategoryFromRole('男主')).toBe('major');
    expect(inferCharacterCategoryFromRole(' 主线反派 ')).toBe('major');
    expect(inferCharacterCategoryFromRole('路人甲')).toBe('secondary');
    expect(CHARACTER_CATEGORY_LABELS.major).toBe('主要角色');
  });

  it.each([
    ['major', 'major'],
    [' MAJOR ', 'major'],
    ['主要角色', 'major'],
    ['主要', 'major'],
    ['主角色', 'major'],
    ['secondary', 'secondary'],
    ['次要角色', 'secondary'],
    ['次要', 'secondary'],
    ['配角', 'secondary'],
  ])('normalizeCharacterCategory(%s) -> %s', (input, expected) => {
    expect(normalizeCharacterCategory(input, '主角')).toBe(expected);
  });

  it('falls back to role inference for unknown values', () => {
    expect(normalizeCharacterCategory('unknown', '女主')).toBe('major');
    expect(normalizeCharacterCategory(42, '')).toBe('secondary');
    expect(normalizeCharacterCategory(undefined)).toBe('secondary');
  });

  it('parses full attribute payload with normalization', () => {
    const attrs = parseCharacterAttributes(
      JSON.stringify({
        avatar: 'data:image/png;base64,xx',
        aliases: [' 远哥 ', '远哥', '', 3, '小林'],
        category: '主要',
        highlightColor: ' #ABCDEF ',
        highlightFirstMentionOnly: false,
        currentState: [
          { id: 's1', label: '境界', value: '筑基中期' },
          { label: ' 伤势 ', value: ' 左臂骨裂 ' },
          { label: '空值', value: '' },
          null,
          'bad',
        ],
      }),
      '配角'
    );
    expect(attrs.avatar).toBe('data:image/png;base64,xx');
    expect(attrs.aliases).toEqual(['远哥', '小林']);
    expect(attrs.category).toBe('major');
    expect(attrs.highlightColor).toBe('#abcdef');
    expect(attrs.highlightFirstMentionOnly).toBe(false);
    expect(attrs.currentState).toEqual([
      { id: 's1', label: '境界', value: '筑基中期' },
      { id: fnv1a32('伤势:左臂骨裂:1'), label: '伤势', value: '左臂骨裂' },
    ]);
  });

  it('uses defaults for empty / invalid fields', () => {
    const attrs = parseCharacterAttributes('', '主角');
    expect(attrs).toEqual({
      avatar: undefined,
      design: { appearance: '', personality: '', background: '', speech: '', outfit: '' },
      media: [],
      aliases: [],
      category: 'major',
      highlightColor: DEFAULT_CHARACTER_HIGHLIGHT_COLOR,
      highlightFirstMentionOnly: true,
      currentState: [],
    });
    expect(parseCharacterAttributes('{"highlightColor":"red","avatar":5}').highlightColor).toBe(
      DEFAULT_CHARACTER_HIGHLIGHT_COLOR
    );
    expect(parseCharacterAttributes('null').aliases).toEqual([]);
  });

  it('returns safe defaults for malformed JSON', () => {
    expect(parseCharacterAttributes('{oops', '女主')).toEqual({
      design: { appearance: '', personality: '', background: '', speech: '', outfit: '' },
      media: [],
      aliases: [],
      category: 'major',
      highlightColor: DEFAULT_CHARACTER_HIGHLIGHT_COLOR,
      highlightFirstMentionOnly: true,
      currentState: [],
    });
  });

  it('人物设计与图集：stringify -> parse 保留；空设计 / 空图集不写入；其他写入方展开旧属性时不丢失', () => {
    const media = [
      {
        id: 'm1',
        path: '资料/图集/人物/林舟/a.png',
        kind: 'turnaround' as const,
        source: 'ai' as const,
        prompt: '三视图',
        createdAt: '2026-10-07T00:00:00.000Z',
      },
    ];
    const design = {
      appearance: '黑发',
      personality: '倔强',
      background: '',
      speech: '',
      outfit: '短打',
    };
    const json = stringifyCharacterAttributes({ avatar: media[0].path, design, media }, '主角');
    const parsed = parseCharacterAttributes(json, '主角');
    expect(parsed.design).toEqual(design);
    expect(parsed.media).toEqual(media);
    expect(parsed.avatar).toBe(media[0].path);
    // 例如 AI 补全人物别名：展开旧属性再写回，设计与图集仍在
    const rewritten = parseCharacterAttributes(
      stringifyCharacterAttributes({ ...parsed, aliases: ['阿舟'] }, '主角'),
      '主角'
    );
    expect(rewritten.design).toEqual(design);
    expect(rewritten.media).toHaveLength(1);
    expect(JSON.parse(stringifyCharacterAttributes({}, ''))).not.toHaveProperty('design');
    expect(JSON.parse(stringifyCharacterAttributes({}, ''))).not.toHaveProperty('media');
  });

  it('stringify -> parse round-trips', () => {
    const json = stringifyCharacterAttributes(
      {
        avatar: 'a.png',
        aliases: ['晴儿', '晴儿'],
        category: 'secondary',
        highlightColor: '#112233',
        highlightFirstMentionOnly: false,
        currentState: [{ id: 'x', label: '目标', value: '寻找父亲' }],
      },
      '女主'
    );
    expect(JSON.parse(json)).toEqual({
      avatar: 'a.png',
      aliases: ['晴儿'],
      category: 'secondary',
      highlightColor: '#112233',
      highlightFirstMentionOnly: false,
      currentState: [{ id: 'x', label: '目标', value: '寻找父亲' }],
    });
    const back = parseCharacterAttributes(json);
    expect(back.aliases).toEqual(['晴儿']);
  });

  it('stringify omits avatar and applies defaults', () => {
    expect(JSON.parse(stringifyCharacterAttributes({}, '男主'))).toEqual({
      aliases: [],
      category: 'major',
      highlightColor: DEFAULT_CHARACTER_HIGHLIGHT_COLOR,
      highlightFirstMentionOnly: true,
      currentState: [],
    });
  });

  it('mapCharacterRows maps DB rows', () => {
    const rows = mapCharacterRows([
      {
        id: 1,
        name: '林远',
        role: '主角',
        description: '少年剑客',
        attributes: '{"aliases":["远哥"]}',
      },
      { id: 2, name: '苏晴', role: '', description: '', attributes: '' },
    ]);
    expect(rows[0]).toMatchObject({
      id: 1,
      name: '林远',
      role: '主角',
      category: 'major',
      description: '少年剑客',
      aliases: ['远哥'],
      avatar: undefined,
    });
    expect(rows[1]).toMatchObject({ role: '', category: 'secondary', description: '' });
  });
});

describe('timeline helpers', () => {
  const autoA: CharacterTimelineItem = {
    id: 'auto-1',
    autoKey: 'ch1',
    title: '初入青云宗',
    summary: '林远拜师',
    source: 'auto',
    chapterLabel: '第一章',
    chapterNumber: 1,
    startLine: 1,
    endLine: 20,
    sourceLabel: '自动',
  };
  const autoB: CharacterTimelineItem = {
    id: 'auto-2',
    title: '试剑大会',
    summary: '林远夺魁',
    source: 'auto',
  };

  it('getCharacterTimelineOrderKey prefers autoKey', () => {
    expect(getCharacterTimelineOrderKey(autoA)).toBe('ch1');
    expect(getCharacterTimelineOrderKey(autoB)).toBe('auto-2');
  });

  it('parseTimelineOrderKeys dedups/trims and tolerates garbage', () => {
    expect(parseTimelineOrderKeys('[" a ","b","a",1,null,""]')).toEqual(['a', 'b']);
    expect(parseTimelineOrderKeys(null)).toEqual([]);
    expect(parseTimelineOrderKeys(undefined)).toEqual([]);
    expect(parseTimelineOrderKeys('{"a":1}')).toEqual([]);
    expect(parseTimelineOrderKeys('not json')).toEqual([]);
  });

  it('parseCharacterTimelineItems validates items', () => {
    const raw = JSON.stringify([
      {
        id: ' t1 ',
        title: '下山',
        summary: '林远离开宗门',
        source: 'manual',
        autoKey: '',
        chapterLabel: '第五章',
        chapterNumber: 5,
        sourcePath: '/novel/第五章.md',
        startLine: 3,
        endLine: Number.NaN,
        mentionCount: 4,
        sourceLabel: '手工',
      },
      { id: 't2', title: '', summary: 'x' },
      { id: 't3', title: '遇袭', summary: '黑衣人', source: 'whatever', chapterNumber: '7' },
      null,
      42,
    ]);
    expect(parseCharacterTimelineItems(raw)).toEqual([
      {
        id: 't1',
        title: '下山',
        summary: '林远离开宗门',
        source: 'manual',
        autoKey: undefined,
        chapterLabel: '第五章',
        chapterNumber: 5,
        sourcePath: '/novel/第五章.md',
        startLine: 3,
        endLine: undefined,
        mentionCount: 4,
        sourceLabel: '手工',
      },
      {
        id: 't3',
        title: '遇袭',
        summary: '黑衣人',
        source: 'auto',
        autoKey: undefined,
        chapterLabel: undefined,
        chapterNumber: undefined,
        sourcePath: undefined,
        startLine: undefined,
        endLine: undefined,
        mentionCount: undefined,
        sourceLabel: undefined,
      },
    ]);
    expect(parseCharacterTimelineItems('')).toEqual([]);
    expect(parseCharacterTimelineItems('{}')).toEqual([]);
    expect(parseCharacterTimelineItems('[oops')).toEqual([]);
  });

  it('mergeCharacterTimelineItems overlays persisted edits, orphans and manual items', () => {
    const persisted: CharacterTimelineItem[] = [
      {
        id: 'p1',
        autoKey: 'ch1',
        title: '拜入青云宗（改）',
        summary: '作者手动润色',
        source: 'auto',
      },
      { id: 'orphan', autoKey: 'gone', title: '旧事件', summary: '已删章节', source: 'auto' },
      { id: 'm1', title: '番外', summary: '苏晴回忆', source: 'manual' },
      { id: 'ignored', title: '无键自动', summary: '丢弃', source: 'auto' },
    ];
    const merged = mergeCharacterTimelineItems([autoA, autoB], persisted);
    expect(merged.map((item) => item.id)).toEqual(['p1', 'auto-2', 'orphan', 'm1']);
    expect(merged[0]).toMatchObject({
      title: '拜入青云宗（改）',
      summary: '作者手动润色',
      chapterLabel: '第一章',
      chapterNumber: 1,
      startLine: 1,
      endLine: 20,
      sourceLabel: '自动',
    });
    expect(merged[2]).toMatchObject({ source: 'manual', sourceLabel: '手工整理' });
  });

  it('mergeCharacterTimelineItems honours order keys and appends the rest', () => {
    const manual: CharacterTimelineItem = {
      id: 'm1',
      title: '番外',
      summary: 's',
      source: 'manual',
    };
    const merged = mergeCharacterTimelineItems(
      [autoA, autoB],
      [manual],
      ['m1', 'missing', 'm1', 'auto-2']
    );
    expect(merged.map((item) => item.id)).toEqual(['m1', 'auto-2', 'auto-1']);
  });

  it('extractLineSummary strips markdown and truncates', () => {
    const lines = ['# 第一章', '', '> 林远**醒来**', '- 苏晴`在旁`'];
    expect(extractLineSummary(lines, 2, 5)).toBe('林远 醒来 苏晴 在旁');
    expect(extractLineSummary(lines, 2, 2)).toBe('暂无内容摘要');
    const long = ['字'.repeat(200)];
    expect(extractLineSummary(long, 1, 2)).toBe(`${'字'.repeat(110)}...`);
    expect(extractLineSummary(lines, -5, 1)).toBe('暂无内容摘要');
  });
});

describe('chapter detection', () => {
  it.each([
    ['第一章', true],
    ['第12章', true],
    ['第三幕', true],
    ['Chapter 3', true],
    ['act2', true],
    ['', true],
    ['   ', true],
    ['第一章 风起青萍', false],
    ['序章', false],
  ])('isGenericOutlineTitle(%s) -> %s', (text, expected) => {
    expect(isGenericOutlineTitle(text)).toBe(expected);
  });

  it.each([
    ['第一章 风起青萍', true],
    ['第一章：风起', true],
    ['第十二回-夜战', true],
    ['第三卷', true],
    ['Chapter 1: Dawn', true],
    ['Part 2', true],
    ['scene 3', false],
    ['第一章风起', false],
    ['', false],
    ['林远拔剑', false],
  ])('isChapterHeading(%s) -> %s', (text, expected) => {
    expect(isChapterHeading(text)).toBe(expected);
  });

  it('selectChapterHeadings prefers chapter-like headings when >= 2', () => {
    const headings = [
      heading('作品简介', 1, 1),
      heading('第一章 风起', 3, 2),
      heading('第二章 云涌', 10, 2),
      heading('  ', 12, 1),
    ];
    expect(selectChapterHeadings(headings).map((h) => h.line)).toEqual([3, 10]);
  });

  it('selectChapterHeadings falls back to top-level headings', () => {
    const headings = [heading('卷首语', 1, 2), heading('楔子', 3, 2), heading('细节', 5, 3)];
    expect(selectChapterHeadings(headings).map((h) => h.text)).toEqual(['卷首语', '楔子']);
    expect(selectChapterHeadings([heading('只有一个', 1, 0)]).map((h) => h.text)).toEqual([
      '只有一个',
    ]);
  });

  it('selectChapterHeadings handles empty input', () => {
    expect(selectChapterHeadings([])).toEqual([]);
    expect(selectChapterHeadings([heading('  ', 1)])).toEqual([]);
  });
});

describe('parseOutlineTitleCompletions', () => {
  it('parses array under items/titles/result keys', () => {
    expect(
      parseOutlineTitleCompletions(
        '```json\n{"items":[{"line":1,"title":" 风起 "},{"line":0,"title":"x"}]}\n```'
      )
    ).toEqual([{ line: 1, title: '风起' }]);
    expect(parseOutlineTitleCompletions('{"titles":[{"line":"3","title":"云涌"}]}')).toEqual([
      { line: 3, title: '云涌' },
    ]);
    expect(parseOutlineTitleCompletions('{"result":[{"line":5}]}')).toEqual([]);
  });

  it('parses fenced top-level arrays', () => {
    expect(
      parseOutlineTitleCompletions(
        '```json\n[{"line":1,"title":"初入宗门"},{"line":9,"title":"试剑"}]\n```'
      )
    ).toEqual([
      { line: 1, title: '初入宗门' },
      { line: 9, title: '试剑' },
    ]);
  });

  it('parses line->title maps', () => {
    expect(
      parseOutlineTitleCompletions('{"1":"初入宗门","9":{"title":"试剑"},"x":"skip","12":5}')
    ).toEqual([
      { line: 1, title: '初入宗门' },
      { line: 9, title: '试剑' },
    ]);
  });

  it('parses plain text lines when no JSON is present', () => {
    const raw = 'line: 1, title: "初入宗门"\nline=9；title=试剑\n无关内容';
    expect(parseOutlineTitleCompletions(raw)).toEqual([
      { line: 1, title: '初入宗门' },
      { line: 9, title: '试剑' },
    ]);
  });

  it('returns [] on malformed JSON', () => {
    expect(parseOutlineTitleCompletions('{"items": [}')).toEqual([]);
  });

  // 回归（已修复）：extractJsonBlock only looks for {...} when there is no code fence, so a bare JSON array
  // with multiple objects is sliced into `{..},{..}` which is invalid JSON and yields [].
  it('parses a bare (unfenced) JSON array', () => {
    expect(
      parseOutlineTitleCompletions('[{"line":1,"title":"初入宗门"},{"line":9,"title":"试剑"}]')
    ).toHaveLength(2);
  });
});

describe('buildOutlineEntries / extractChapterContent', () => {
  const content = [
    '第一章', // 1
    '林远在青云山下醒来。', // 2
    '', // 3
    '苏晴递来一碗药。', // 4
    '第二章 试剑大会', // 5
    '剑光如雪。', // 6
  ].join('\n');

  it('returns [] for blank content', () => {
    expect(buildOutlineEntries('   \n ', [])).toEqual([]);
  });

  it('builds one untitled entry when there are no headings', () => {
    const entries = buildOutlineEntries('林远 醒来\n\n苏晴', []);
    expect(entries).toEqual([
      {
        cacheKey: fnv1a32('未命名章节'),
        line: 1,
        level: 1,
        text: '未命名章节',
        originalText: '',
        summary: '林远 醒来 苏晴',
        autoGenerated: false,
        needsAiTitle: true,
        wordCount: 6,
      },
    ]);
  });

  it('builds entries per chapter heading with summary and word count', () => {
    const headings = [heading('第一章', 1), heading('第二章 试剑大会', 5)];
    const entries = buildOutlineEntries(content, headings);
    expect(entries).toHaveLength(2);
    expect(entries[0]).toMatchObject({
      line: 1,
      text: '第一章',
      originalText: '第一章',
      summary: '林远在青云山下醒来。 苏晴递来一碗药。',
      needsAiTitle: true,
      wordCount: 18,
      cacheKey: fnv1a32('第一章'),
    });
    expect(entries[1]).toMatchObject({
      line: 5,
      text: '第二章 试剑大会',
      summary: '剑光如雪。',
      needsAiTitle: false,
      wordCount: 5,
    });
  });

  it('extractChapterContent returns body between headings, truncated', () => {
    const headings = [heading('第一章', 1), heading('第二章 试剑大会', 5)];
    const entries = buildOutlineEntries(content, headings);
    expect(extractChapterContent(content, entries, 0, 1000)).toBe(
      '林远在青云山下醒来。\n\n苏晴递来一碗药。'
    );
    expect(extractChapterContent(content, entries, 1, 1000)).toBe('剑光如雪。');
    expect(extractChapterContent(content, entries, 0, 4)).toBe('林远在青');
    expect(extractChapterContent(content, entries, -1, 10)).toBe('');
    expect(extractChapterContent(content, entries, 2, 10)).toBe('');
  });

  it('handles CRLF content', () => {
    const entries = buildOutlineEntries('第一章 起\r\n正文\r\n', [heading('第一章 起', 1)]);
    expect(entries[0].summary).toBe('正文');
  });
});

describe('inferCharacterCamp / inferRelationStage', () => {
  it('uses role keywords first', () => {
    expect(inferCharacterCamp(makeCharacter({ role: '女主' }), [])).toBe('protagonist');
    expect(inferCharacterCamp(makeCharacter({ role: '最终反派' }), [])).toBe('antagonist');
    expect(inferCharacterCamp(makeCharacter({ role: '宿敌' }), [])).toBe('antagonist');
  });

  it('uses relation balance otherwise', () => {
    const c = makeCharacter({ id: 5, role: '长老' });
    expect(inferCharacterCamp(c, [])).toBe('protagonist');
    expect(
      inferCharacterCamp(c, [
        relation(5, 1, 'rival'),
        relation(2, 5, 'rival'),
        relation(5, 3, 'rival'),
      ])
    ).toBe('antagonist');
    expect(inferCharacterCamp(c, [relation(5, 1, 'rival')])).toBe('support');
    expect(
      inferCharacterCamp(c, [
        relation(5, 1, 'rival'),
        relation(5, 2, 'ally'),
        relation(8, 9, 'rival'),
      ])
    ).toBe('protagonist');
  });

  it.each([
    ['', '未标注阶段'],
    ['  ', '未标注阶段'],
    ['初识于山门', '前期'],
    ['矛盾升级', '中期'],
    ['最终决裂', '后期'],
    ['一起喝酒', '阶段未定义'],
  ])('inferRelationStage(%s) -> %s', (note, expected) => {
    expect(inferRelationStage(note)).toBe(expected);
  });
});

describe('buildCharacterLinks / getRoleColor', () => {
  it('links consecutive characters, max 5 links', () => {
    expect(buildCharacterLinks([makeCharacter()])).toEqual([]);
    const chars = Array.from({ length: 8 }, (_, i) =>
      makeCharacter({ id: i + 1, role: i === 1 ? '' : '配角' })
    );
    const links = buildCharacterLinks(chars);
    expect(links).toHaveLength(5);
    expect(links[0]).toEqual({ sourceId: 1, targetId: 2, label: '待定义' });
    expect(links[2]).toEqual({ sourceId: 3, targetId: 4, label: '角色关联' });
  });

  it('resolves role colours exactly, by substring, or default', () => {
    expect(getRoleColor('主角')).toBe('#4ec9b0');
    expect(getRoleColor('最终反派')).toBe('#f14c4c');
    expect(getRoleColor('路人')).toBe('#b5cea8');
  });
});
